apiVersion: v1
data:
    QUARKUS_DATASOURCE_JDBC_URL: ENC[AES256_GCM,data:6ABEvjKlyt7Ij2II9FMpYjNpUKPoTWbQvlUG/UCqFURrUdbV6QfTZ4G7ZW04Bpzthx30J4fwN4m8KaaEcuhtvqP9DxqB8K78IBRivbiCxHZYuY5oZtyHOOa+bloBcGg8jYU1eA==,iv:Oll2BJosCC/5Zi1hB26oRif+MSfBd6xU0mZJG+6kLMU=,tag:c+/e+N6UOcBjkqaJGbhJ0w==,type:str]
    QUARKUS_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:w5YZuNiUdhY9L9pRAaE76zc/iK1gNXQraz5EEy8g3+Em3mScpr9RICJn6oM1QAG3JUoKRGBMoqfa2eJioN1Ggd+wNFs09F3J3cxDL9uwCZlm7nozv+44bQ==,iv:Sg+56CmwDy/ILlcP5TdwHb7aYzKARkaaushJG6LHyOo=,tag:kDuS3WzisioLRqpMLKt8/Q==,type:str]
    QUARKUS_DATASOURCE_USERNAME: ENC[AES256_GCM,data:T3M1Tg==,iv:KWUweLTB5hm47TrWYm06HOKrFmCBLwDHXzJWBtYzFBE=,tag:6i6r2F5Ep5LaOugFmF6bvA==,type:str]
kind: Secret
metadata:
    name: commafeed-db-secret
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTGw0OVZYcGtoSjM5WTBa
            dE1ialBtL0dPK2pqNGk2Wk0yaDJtb0d1U2xFCk9TVk9NaUo0Q0k5c3NsMTk2QWhh
            ZzRjNmdHYUlWSTdKY2tEZDBwZUIwRkUKLS0tIEw5TDg3dzc0Z1hDNGp4TEhpL20v
            Z055aUUycHNrUmVXeDVqSlZLRko4blEK4Ni0XoeAp5Wj7wGy4kd+a7S2vxOS2hwR
            UcH8sc5AWx5jt6nxpo5/4F9ueIQW2R9mbzHdpIi2KAV5HC5Be1nWaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T14:08:04Z"
    mac: ENC[AES256_GCM,data:68M9rHyo4OJcX+z4R9FkHi+wFNWzqYG/IsLUHJbM6AqIo3KBI6GPs/RTURM5fuyOYya1ODXJetxLM15ARs8ugmI9iUmDkw+25ryxgFIbXuMYr96HStRomw8AgVn/sJm1DkJVa0vh9ltu1QyNPvbq1pwcCHf8/CWilT9v8csyxtA=,iv:TKjYWwitETLfAe2aNf03D3e1iHRYFbmA5bVmsgG6oNY=,tag:tyQHv3klVbum7f0o5+yqxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
