apiVersion: v1
kind: Secret
metadata:
  name: commafeed-db-secret
  namespace: commafeed
type: Opaque
stringData:
  QUARKUS_DATASOURCE_JDBC_URL: ENC[AES256_GCM,data:4fThs7yQ5BOMEn6cvLX76aCx7KYa9ysMSmIHNG+iDn0oQq1qKHLB/Ek+cqYWovCwFwYK/PunRcYLB9T4RrTjXCPv9VJX+HcgEF2b5BJMP3jF+Qw=,iv:NQsMio/1xOGjvkGDMrkz+XvN5F6YGiUkbQnDS1jnd2M=,tag:+U2SyaW17IlUe4ASFOOeGQ==,type:str]
  QUARKUS_DATASOURCE_USERNAME: ENC[AES256_GCM,data:dhnA,iv:GKN1wLkmYUFBpg3RSCK8aJXZFRKD0zbRGqLvYF1d10Q=,tag:nmZbzzhoGbYJBbdQr1izrQ==,type:str]
  QUARKUS_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:YRHYTY8LpbZraQYd7hFA,iv:PSZV+k6ZL9NzvMbD6KilrKSBgz+mCo2ixpC8LDBURe4=,tag:eZ0dzNUll1W+tUyTltzCnw==,type:str]
sops:
  age:
    - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUkhhR1RsVE9aQVNJaWpG
        akl6VTJRYmM0bUxKdG1vRy9xbE00WXRoWWlBClRXYjhRVEtKZHlpSVJVMC95MFNS
        bUF5K3lmb01uUkJXRG9pTzd4cWVGSEkKLS0tIFZnS2VPYTg5SmZwb3hDVFZsTStj
        dlMyNk1YMS82SGhmN0V5QldSeElHOWMK7Jw5v7jewfRfjA2aHsy8HRAtG29p4BdF
        O5yZpvO5sc6p3W1CqkpOi9Q6Z5jNNzqWGgSBLNyVwrpx8zBcs/2cQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T12:25:58Z"
  mac: ENC[AES256_GCM,data:Ri2TfvE1uqPrYeJp6E3I6HEYlnZ/MslGLS88vV+XOm/nKYqcT4cShmKJjQBrgQqUyLMxEmorv2rfZA+DSupLxoxHsuiLJp4kUhtNB6gX90+9j/osIYaj4LntJKsyEa9dODBK4ptMm34qRcT5+1KTo1U+p0EjVntt/T8nxlfVIww=,iv:GuTMBcD1QPAcFNALmfWOy27AzkK9FndtBAojXZfpf48=,tag:j+jRW5lp194NYooEpjJN+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
