apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:k92zw05a+zA=,iv:FOHrmUTo6Oolx7ZEjzSNM2lItJDl/2RFPMraWV7li28=,tag:mFgAXPjnXXJo0IWcjwBE8g==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:Oab+t7y6Ro6mTWRFhwXxoA==,iv:fJRmxipOiF3YWTvOGMan1AxW3i77Ks1IzBWz4Lnc9S8=,tag:Jw8jpA79i0LMvbJ+6tM6Mw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVVB4YTd2T0pOdnNyVVBC
            YVdxV25lRUxlWVcyWVc4NjlBcUw5VXMxQUhNCnBXWEFjVEhjekNXMnNHK2dpaWtE
            bG55Q0prcXk3Z0xRdDlnZzhqNlFjRzQKLS0tIDB4cEdiSUxESUZaeVorWGdFRVhy
            MlEvUmthcFo2KzlVNFgxaFBEcVk4elEKbJ5Qzhl7QhSyEv+jWpObu0vQoPyAvh3f
            Vurd55YtDk5xC+pt89SkFvJz+iKqpPOcjr4ueknPsMVOs8TevPRpKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WDd3Z1BjYkpsMzlHTGpY
            MGtvVmVVY3lxREwvR3EwWlloL0hYTTNFVnpvCjd5akxMT2hibXlEeTBmN281REFX
            RDY1SGxKaDN2UXFJSTRPTkJVTnh1dDgKLS0tIFE0ai9scFFmcDdNblpscis2VFI0
            TUU2d3lxMkJXdnhBSEd2RyswSTV1T0kKriFgm6CowqcoLgNJGjW0rjmNNxNFtdZ5
            8VdE5ZozY+6UltDckyWoO1L3BjyY6vJAr4gh3/fccMhz+7iNtOUXRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-11-29T16:17:16Z"
    mac: ENC[AES256_GCM,data:suuH8R9R5DdP/Pvxkb5Ye9rutMsSnDl8MZDQx1C/51i243U8SVOrqlpg7BSBGJ4lw8rIdEorZQwP11mcz+R5mnqSSYwBM127Y0qu0k3qeo0zBEWvZaHUprK4eczutwe47SNdFv8WyTQfcglStyzvS0RYxoG5voVsTZAKXdS6kyM=,iv:Ne88UcL/erw2ZURfpKfx1xldr574E8yaHWGqyYs87eI=,tag:Jq4eQ9z5yrMR+vjTKGVoQA==,type:str]
    version: 3.11.0
