apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-nfs-production
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.ronaldlokers.nl
    path: /mnt/tank/media/immich/production
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
