apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - postgres-credentials-secret.yaml
  - postgres-credentials-mirror.yaml
  - immich-config-secret.yaml
  - network-policy-oidc.yaml
  - ../../base/immich
  - immich-library-pv.yaml
  - hpa.yaml
patches:
  - path: values-patch.yaml
    target:
      kind: HelmRelease
      name: immich
