apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  services.yaml: |
    - Bookmarks:
        - Linkding:
            icon: linkding.png
            href: https://linkding.staging.ronaldlokers.nl
            description: Bookmark manager

    - Search:
        - SearXNG:
            icon: searxng.png
            href: https://searxng.staging.ronaldlokers.nl
            description: Metasearch

    - Media:
        - Commafeed:
            icon: commafeed.png
            href: https://commafeed.staging.ronaldlokers.nl
            description: RSS feed reader

    - Food:
        - Tandoor:
            icon: tandoor-recipes.png
            href: https://tandoor.staging.ronaldlokers.nl
            description: Recipe manager

    - Health:
        - Nightscout:
            icon: nightscout.png
            href: https://nightscout.staging.ronaldlokers.nl
            description: CGM remote monitoring
    - DevOps:
        - Grafana:
            icon: grafana.png
            href: https://grafana.staging.ronaldlokers.nl
            description: Metrics and dashboards
            widget:
              type: grafana
              url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
              username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
        - Gatus:
            icon: gatus.png
            href: https://gatus.staging.ronaldlokers.nl
            description: Uptime monitoring
            widget:
              type: gatus
              url: http://gatus.gatus.svc.cluster.local:8080
        - Flux:
            icon: flux-cd.png
            href: https://fluxcd.io/
            description: GitOps continuous delivery
  proxmox.yaml: ""
