apiVersion: v1
kind: Secret
metadata:
    name: homepage-env
    namespace: homepage
type: Opaque
stringData:
    #ENC[AES256_GCM,data:iYfU8V6SScjAUnUVuupcCmxdGuw=,iv:VlV7VzXiOqqVzacFZ7BMF+gJK33MT3CJB0Vjtcr/lwc=,tag:exkEyA8Z6+r5ysJtgUeMoQ==,type:comment]
    HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:PHJ3euU=,iv:o7mGUPPqv7E/ArIaF9w3sXF1udOFlqm+qsVDF1w/3sU=,tag:a1pySwQUmxTKzVIqjvaejw==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:dW1E1vnJ,iv:95eLagbpNs/sPlTQTNvp5XZGxBk32tYBFbjbokuO6Nc=,tag:GNutfwFftkAkdiob8DnIfA==,type:str]
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSzlmNEJuNTdHSVE4SnNj
            YU94RTRsU3ZMRThuc2VzS1hhSGhYbVl3NnlRCnRFRlhiREpwK0hTVGdkNS9abmtE
            NjNoTEhCSFBmcXhTZWhxdy95MithcGsKLS0tIFlkanV5TENVblYwQ1JSNzhDbjk5
            Nm9BTDB6TzlOWWR3VFUyVHNrdUdVSDQK5U2Y37RmKdkHB5STHQOgX3GU1gwb71TO
            r85EB9GngcVDDW8hqy478Y4B2NnpE+LSdUg5ut0r++3zObreyw6SMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T23:11:04Z"
    mac: ENC[AES256_GCM,data:Ng6/HJwv3JVB0NFNJ04EGZLg27xCWdr5mIHaq7vDRArkDQWsG5hISwqH4Ls4fIFl8OLI8Hf9xgmroW+ED6WjNAP6P2VOwxxkWscXYVXzYpl/V3VaNJv+W9dIgC1btrb2oxywKTk2WphYZF4B8ncLBJAedjA1jH9DlkWDN5dtfj0=,iv:uNJOAuBmBbIZzxtwk9kwJZXKVRRG0RO9/zkdfGFZCU0=,tag:6vI4fN03DHBx3vi7qwYArQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
