apiVersion: v1
kind: Secret
metadata:
    name: homepage-env
    namespace: homepage
type: Opaque
stringData:
    #ENC[AES256_GCM,data:iYfU8V6SScjAUnUVuupcCmxdGuw=,iv:VlV7VzXiOqqVzacFZ7BMF+gJK33MT3CJB0Vjtcr/lwc=,tag:exkEyA8Z6+r5ysJtgUeMoQ==,type:comment]
    HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:PHJ3euU=,iv:o7mGUPPqv7E/ArIaF9w3sXF1udOFlqm+qsVDF1w/3sU=,tag:a1pySwQUmxTKzVIqjvaejw==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:dW1E1vnJ,iv:95eLagbpNs/sPlTQTNvp5XZGxBk32tYBFbjbokuO6Nc=,tag:GNutfwFftkAkdiob8DnIfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtckFSdXdUbC9yQlF4dDVn
            T1VxREVJTVlja1JjYTlPY2R3d21FY1BuSW1FCmRrZjJhLzc4NGV6b2tvZXJhTGJn
            ZUFLZXhodXBpYUtuUmZQdWY0UzdzcFUKLS0tIHhWMjNtbm5BY3I3aWxjQndQakRa
            NG1kQitPRVpMNkFLZWtMa1drWm9zUW8KjxlTzEW6FvsVWfyv0/IrhwnWe4WRWDQL
            5MuMew+ZcA+Fm+chRYyk6/YvwWznZLPguTtOmuL+NTEoFh0Re+2SNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS0RXUDVaUlhFV013Nllr
            VU9ncDByS2xtMzRwcEprbGRJUU10L3VhdGljCktDSjVOMFB3Y1ptTG1KT3pOQlBi
            dHRFNUxuTFlMcktPK1RYMHBkTC9xUzQKLS0tIDZIQzZmN2pIT3pmWXo1RGJlL3BE
            K2lsWW94ZW5Md3FYZ3NqejFmSS8yY2sKgGyTtXDQ7d9sZR9+YtMwrAFnve8JGwss
            q+SXk5GyNowWImUAQRZ4eraraeiL78LEt8wfvcv5JnxAwWbZhvsRYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age146l4mqkpljck0n9gfncn2te3yqu0s25xyn3438j2pfmg0u4zju2s6fyvrv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-02T23:11:04Z"
    mac: ENC[AES256_GCM,data:Ng6/HJwv3JVB0NFNJ04EGZLg27xCWdr5mIHaq7vDRArkDQWsG5hISwqH4Ls4fIFl8OLI8Hf9xgmroW+ED6WjNAP6P2VOwxxkWscXYVXzYpl/V3VaNJv+W9dIgC1btrb2oxywKTk2WphYZF4B8ncLBJAedjA1jH9DlkWDN5dtfj0=,iv:uNJOAuBmBbIZzxtwk9kwJZXKVRRG0RO9/zkdfGFZCU0=,tag:6vI4fN03DHBx3vi7qwYArQ==,type:str]
    version: 3.11.0
