#!/usr/bin/env python3
"""Rasterise real typefaces into `glyphs.py`, a plain-Python table.

Run on a workstation, never in the cluster:

    python3 -m venv /tmp/bake && /tmp/bake/bin/pip install pillow
    /tmp/bake/bin/python bake_font.py > glyphs.py

This is the whole trick that lets the chart use a real typeface. Pillow and
FreeType do the hard part here, once, and what ships is an array of 8-bit
coverage values. The CronJob still runs on a stock `python:3.13-alpine` with
nothing installed — no wheel to build for arm64, no base image to maintain.

Each face carries only the characters it actually draws. The hero number is
96px, so its glyphs are ~6KB each; including the alphabet in a face that only
ever renders digits and a percent sign would quadruple the module for nothing.

The fonts are the ones already on an Omarchy box. Adwaita Sans is Inter-derived
and holds up at small sizes; JetBrains Mono is used wherever digits should line
up in a column, which is every number the chart draws.
"""

import base64
import json
import sys
import zlib

from PIL import Image, ImageDraw, ImageFont

ADWAITA = "/usr/share/fonts/Adwaita/AdwaitaSans-Regular.ttf"  # variable
JETBRAINS = "/usr/share/fonts/TTF/JetBrainsMonoNLNerdFontMono-%s.ttf"
# URW Gothic is the Avant Garde clone, and the closest thing installed to the
# geometric sans the Vienna Method's charts were set in. Chosen for that
# lineage, not for being available.
GOTHIC = "/usr/share/fonts/gsfonts/URWGothic-%s.otf"

LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
DIGITS = "0123456789"
PUNCTUATION = " .,:%/-()·!'"

# name -> (font file, variable-font instance or None, size, charset)
#
# Sized for the box Campfire gives the attachment, not for the file. It renders
# the image at 1017x1200 device pixels, so 34px of body type here is about 11
# CSS pixels on the phone — near the floor, and nearly twice what the previous
# 22px managed on a canvas that was being downscaled to fit.
FACES = {
    # The headline finding, which is the first thing read and often the only
    # thing read. Two lines of this is the whole top of the sheet.
    "headline": (GOTHIC % "Demi", None, 56, LETTERS + DIGITS + PUNCTUATION),
    "body": (GOTHIC % "Book", None, 30, LETTERS + DIGITS + PUNCTUATION),
    "small": (GOTHIC % "Book", None, 26, LETTERS + DIGITS + PUNCTUATION),
    # Figures are mono so a column of them lines up as a column of figures.
    "stat": (JETBRAINS % "Bold", None, 42, DIGITS + "%.-"),
    "figure": (JETBRAINS % "Regular", None, 28, DIGITS + "%.-:"),
}


def bake(path, instance, size, charset):
    font = ImageFont.truetype(path, size)
    if instance:
        font.set_variation_by_name(instance)
    ascent, _ = font.getmetrics()

    glyphs, bitmaps = {}, bytearray()
    for character in charset:
        left, top, right, bottom = font.getbbox(character)
        width, height = max(right - left, 1), max(bottom - top, 1)
        # Two pixels of slack so an overhanging antialiased edge is not clipped.
        image = Image.new("L", (width + 4, height + 4), 0)
        ImageDraw.Draw(image).text(
            (2 - left, 2 - top), character, font=font, fill=255
        )
        glyphs[character] = [
            image.width,
            image.height,
            left - 2,  # x offset from the pen
            top - 2 - ascent,  # y offset from the baseline
            round(font.getlength(character), 2),
        ]
        bitmaps += image.tobytes()
    return glyphs, bytes(bitmaps)


def main():
    index, blob = {}, bytearray()
    for name, (path, instance, size, charset) in FACES.items():
        glyphs, bitmaps = bake(path, instance, size, charset)
        index[name] = {"order": charset, "glyphs": glyphs, "offset": len(blob)}
        blob += bitmaps

    packed = base64.b85encode(zlib.compress(bytes(blob), 9)).decode()
    sys.stdout.write(
        '"""Glyph coverage bitmaps. Generated by bake_font.py — do not edit.\n'
        "\n"
        "Regenerate with:\n"
        "\n"
        "    python3 -m venv /tmp/bake && /tmp/bake/bin/pip install pillow\n"
        "    /tmp/bake/bin/python bake_font.py > glyphs.py\n"
        '"""\n'
        "\n"
        "import base64\n"
        "import zlib\n"
        "\n"
        f"INDEX = {json.dumps(index)}\n"
        "\n"
        f'_PACKED = "{packed}"\n'
        "\n"
        "# One byte of coverage per pixel, faces concatenated in INDEX order.\n"
        "BITMAPS = zlib.decompress(base64.b85decode(_PACKED))\n"
    )
    print(f"# {len(blob)} raw -> {len(packed)} packed", file=sys.stderr)


if __name__ == "__main__":
    main()
