apiVersion: v1
kind: Secret
metadata:
    name: campfire-status-bot
    namespace: campfire
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0zgsAoxNDwwG8hTU7FXI3UqDiIpJTVGKUK/JCxJP+GcldEGvKK+9Dd6H8ilp0ai1WF2w/GPX3IpWMMAx+nHkOwFwRey7zwYw4Sdl,iv:8ZkCnVl+kZIMYfl+lV2FQWFuKCkrYSpBMV96hHeFTqw=,tag:uEm+Txvgkdd0bCYXTVcjIQ==,type:comment]
    #ENC[AES256_GCM,data:/MbEIr/QJAOCzhiV+kptAa7/XsZWPJ+ChuH6EBOEg44cIM1e8E2t41mbiDoRMGPXcBSMkgT72aI3jz/GWli2,iv:xT2PjN2eIXAYJlIJhLvej+BS8mFVF1ExcVq6qG9RIfQ=,tag:+KAVK4f0ipnzUQdY1X8csA==,type:comment]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:9Gwu8H2UpgrNqYpQpokF5wT22R401YFyBfwb8JVbo6t7o9Nm6FfNzHVxnjEoCHsLmu8OGWSgeWWwF6ZbAdnYKEARnfpFG+UEkSgN04d523GbT2blr17Q5HaZtRykotWdwWHDJZsFRuBncM7z,iv:7LZPZWLZl/yilueiQBLGp0NXd92o2QFkqpn4ikXRgwY=,tag:ctB5rVdbmFszRjqKJF5btg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN0VZdG0rQzEyZTh6eldv
            SVRDaVZPcjVkSVV4YnBjVldXUWRabnZnVHdFCndQSGcrNFF6aFgrQU40ZEhEait1
            UlpqR0lTNmJWYndDZVpUZmcyVEV4ZmcKLS0tIFhQcGdQVmpkR1ZrcGs0bjZla0dD
            UE45c01UM2cvb0RYY2M3NDlvWXFvZjgKtRwwiHEQ31jG6gzOgSpnSYRAoqntGIQ0
            ApCD4e/O6ji28aJ2B3JN2THvJdxvWVWQZCPg9bfwdgFyeryRWpa1rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T23:28:00Z"
    mac: ENC[AES256_GCM,data:Ju9lqeoa/YcfzZMBcu3ZjV43HnAx3r5Zu6s8xCt60QuAYVZlGZKbdXqU2bWEHVJ62MVx5wQpTcswetes58cx+0w4J7XuKwvxTzVE1wppldreT6jd++/uIV+yiZhY1v3Glgzk/PRKsnSVSDNFbw8E5RemmHGJ0F/b7tbT/7ecYYo=,iv:PTRouFRixUeLc50KJ8VnITTigAFWbjwge4cGROBA/1k=,tag:IvkuKX6tb820V6WvgY2dBA==,type:str]
    version: 3.13.3
