---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - kustomize-controller
          - notification-controller
          - source-controller
  podMetricsEndpoints:
    - port: http-prom
      interval: 30s
      path: /metrics
