apiVersion: v1
kind: Secret
metadata:
    name: ferretdb-url-secret
    namespace: nightscout
type: Opaque
stringData:
    FERRETDB_POSTGRESQL_URL: ENC[AES256_GCM,data:tyqzteLbZ3w1TOr5ijoDm0P/PYz0TWByhxT4AeV/HcvLh0J5y0cMiV9XeDj/phs1vorm60E5MBdGttzl80I4fagKQvVgF1Fsa0/Z,iv:1xRVYYXA2TyLlLhXNx2AK8B/B0IwZElonNDq/aP45Ko=,tag:/TqNujPkt/zZgvHlP/CLQg==,type:str]
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVi9Rd2FXaWF0YmpwK1h5
            VUg4V0lITDRIREViR2oxUzdoNVR4eURlT1QwCkw1dFZmeVZPbTN6MTRhRzRJZnNq
            aVg4TmF0R25HS0c4NExQcnVKbzArK2MKLS0tIFB6L1puY3hzRGhqYXUrU2tQR1FE
            WE5tN1l3cVp6Wk1Ubnp3R3BsZTFObGMKj3qtrny/WqFz5k29cj8mNxVfVvCXGoQY
            uL6EM5ub54lbmXGwdrF+aQh1tW5vnkdBqWV0KqaMkDXAliE3FiJ7Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T19:20:44Z"
    mac: ENC[AES256_GCM,data:RiHU4dLB1q84oJeLde9ryTycADY5UVd2p3PrGeZb3hZj9bajRUwbMl8JJRfDA36LXDuRAYpzlkC7Y7/fwoyh64KgV0IFK54T61VWKxu4+n80akCjaUx35qOuatG3196/rZaN9eF7Gfw/RusB5yKsXdRCtJPmXGeic2Csp9NzSBM=,iv:X58tkuMTxsIeeUBn+edY/ONuXDqlwoi/UieCIHFI7+I=,tag:haGQRAY1MeCCp2/Uh6qQwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
