apiVersion: v1
kind: Secret
metadata:
    name: nightscout-env
    namespace: nightscout
type: Opaque
stringData:
    API_SECRET: ENC[AES256_GCM,data:BGSrDLRWUwIkqgcHL8sVfCkDfp39kfpPMmi27rxAuMLiKss1DgTLeoT1tauexHvB2kxaiNACxH+D1FdrM4L3vQ==,iv:Yr7pqJnhjb2Wcd69ffCi42XdyHXcg+HpjNyJKEPbVvA=,tag:HyVLP2jdXcUmZwFdLcmW1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa0w4eFkxZ2pUZ0dMZEhl
            MldPd2t6aVdHc3crK20rVDByclVaNzJDeFMwCkdpcjRyenhmSE94d3luUDNCUDZn
            TUdCTHp0Mlc1RUJVN051cS9hSi94T1UKLS0tIEtETDJOUWhBR1lwQi9xaTQyTmJk
            TWNBNDNUeXc4OU1ucjRnOTJhS3h0ZHcKsixPhT4SdPs4MXij9A7WjwMi8RR6BB8+
            ClEwE6tMqjxmsptfHQfWjOzjhdh/GSZq2o+ZAWy7nLn0rZKYahh7sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Yy9KV3hWK04vc2EraGYr
            b3NMMUJuaWpSNXJzOWRtZ2NEREhQRU1jMmprCmRJVGovR3M4K0ZFSWhsMXJUaWY5
            M1JLa2lqaWk4UUIzUEgxZjJESUZLVzgKLS0tIG4xM1JxdGRsdGt0d1ZZNHV5aVRK
            NnpXVjVQbmQzUHRUc3VaQnhtajI4cXcKGRi2cTsZKmikee81FLidQxohO/mKamys
            mtG0hdZopB+lBsetRpedI5Y077DB8YkC/mY7pMHygu1wGDJE+S+FmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age146l4mqkpljck0n9gfncn2te3yqu0s25xyn3438j2pfmg0u4zju2s6fyvrv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-04T10:01:12Z"
    mac: ENC[AES256_GCM,data:XKyOHyJZYilA5RfHI6nODNCYySPZ5WxajxmjgsKHXG/VF2DYUkCF9DEkfIDXDqM54qdBeilIePeUNRQssI8rT6hsuxUjIaNah/Zg6Rf7IK3RJGEmYVefUkmYn0Kxq9wmK9ZgTb7x6A7PJTJAL3IoL/ll1ja+3yYVek9q9Jh/ITs=,iv:9ViDkej1iShb1NaBw8CxMEPN6jySMEfqnOzQtfdCVzo=,tag:XPtJV+ZH5NFwXhAZQoaPHA==,type:str]
    version: 3.11.0
