apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:OAn8XFVYkxFzAilN451FHGs=,iv:DrLgBRiEFDweWj6CsmDQZswq1jYkIpFqpHhYrWH88lI=,tag:Gd50brmeJKBDjYlOeGHTiA==,type:str]
    client_secret: ENC[AES256_GCM,data:iQKciO+LFFo4CrcWQdBYuYu89GxpjYq8Arggi2k3YjucQULond9LegcPQb36i2wglYW3sl4mA1qPvgI3FHRadQ==,iv:dJBIoWbgbL6o6Oxq0ycPyuEpEEjBQVQpPML+IK1gdjc=,tag:M2ghdUmE9En2pgdZ8Jp6dQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUUJVSG9ibTlCY2ZTNlh3
            MWdIL3EyaW5hRDJJSlJEa01vRWI0K0VIWXhNCjhCY3lwM1hyY1ZIRGxiNjU3VERJ
            SndqL1dxeWFaRVFWUHFUcXllaUh2RHcKLS0tIGhWSlJtWEpuaWwyaUVUR2RxK282
            U3V1UERGanhMak56dk93SzJNc3ZhN3MKqDhbr6BFVEbthp9InahHUAafc9pwK0jI
            JOqM3Pl/nCC7fVZUJRT2oZDIYpGgmtEMcpgNWpCa4t2+GTbBAAFkDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T21:31:47Z"
    mac: ENC[AES256_GCM,data:62g/PjUK+Ofv4BPlrwLE83jNYjHglqypCDb/hxZxdXiX/ZJMlsoEEwSuPQ5UdoyzSR99ZNycm0H+hFVWAvUsHNmOMdl+JV62mZUrTkvSKAIN5LEDrS2VZ4A75ixPW7xU5cSUtW6TuY1arcKnAJoj6fQdNkhOlO1SPmz3FF0G7ig=,iv:DOYROsSFKDwEos0s/ml8I231gpwE/a9EXn5wWKCfv7g=,tag:XpE3+1Rc7LMF6mOd4m1fZA==,type:str]
    version: 3.13.2
