apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager

patches:
  - patch: |
      - op: replace
        path: /spec/chart/spec/version
        # renovate: datasource=helm depName=cert-manager registryUrl=https://charts.jetstack.io
        value: "v1.20.3"
    target:
      kind: HelmRelease
      name: cert-manager
