apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-config
  namespace: speedtest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
