apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:UZa0gBmAM0Kp8q1mFmYnS90Ifiw+DzaoVz/f837Dm8z80GPS6jyQ6Q==,iv:z4oBr+eZzEYEiK3wcxmCSLg5jvNGSsoKBsednXgZMkc=,tag:pQKhlLmZ0p3idrB/G493og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcllUL2VLZDVRZ3YwMUR1
            V0s4QllYcW44Y2xGV3Rhb3NLVVQybFBlRUR3CkQyaWozZU5pVE1JSitrSjVxamIy
            b3ZzQmJ1Q1BrS25mbUNMOFJCVjg0Y2cKLS0tIFdhNk5nZ2RnMkZIRTRqbDR2Z2tl
            bDZEejFiUlE4aHd2U2Vpak5KcDFlZkEKDVhwe4UZ3bz8qWc4JR52DDF1DzxfwVB5
            VrE27dBKsplbUFgE/xgoR1CJh2EuutQQGCP21PbFnIAbEsb8wdv6ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTEs5YWRBdWpqNFFNNVY4
            MEFxT3ZQcENIOU8rTno5U2liQU9ybThZTlR3Ci9oR0UwMm9wN25ocUtrSng5MVky
            VTJyVHBrR29OYkJmWU5kUmhFMFhOWEUKLS0tIENaKzNCMjk4WEE1UW4rblA3K09R
            NTRabFFYcW9HWHM5ZFZoVGlGNXcrK2cKPa+uFDHPwr0x6835eQAWi7kmgYUqYi5c
            dmwiLEaDXJrN2I8d/0uVfIXBtDkQJNpGaIHxq8DxhbxufiIlRdA+WA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age146l4mqkpljck0n9gfncn2te3yqu0s25xyn3438j2pfmg0u4zju2s6fyvrv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-02T15:07:45Z"
    mac: ENC[AES256_GCM,data:Bduk3IX5mGrbKdFP3Wwwi4h3S+GaSD/RBqhZsGHFohF/NQDJbNbIRtU4EbRWfQiXGXm2z2G44SxSZ6n5gVnRqjSNLJm+qYtumGeJtO0MV9eXvkANam+QGodMqm4lcmdIHHQnhPEomLL44/ukbuFTEgnd7gdOj7Cnv3V/uspnwKA=,iv:VmG8LAPh90NM1YwpI4Um+D2p7V7wEFGNVOa7RTtPGOg=,tag:YZKkbL7/Ux3bF3jjH5QeUQ==,type:str]
    version: 3.11.0
