apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Myr+20juoE/j61fehH3pmFBYSb4mlPSoYPtOuGLFazDd8jqWkwrjsQ==,iv:t5iCORsG7yGlUUJw6drjqz8+DYkvrWvWhlMSSFpfYBE=,tag:GbtFJbN8VZPBfFaINBhYiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWUlPek1pOTNiNjAzRmla
            bi9mb1k0SU9CNlNSdUxwZ0MvRkhjeTFXeFdFCm40eGQweU5jYjB0cXBnY3dmcldD
            Rk1KL2J3K1NaVC9KdkNmdnp2WmRjMHMKLS0tIFhUdkQwMCtGSTZNYWF6dTU3bGhC
            YnB1Z2RDbUFUWEtPaTAxUW5CdU55REUKcNrxewXrUtVxL8TbdIQOrkpF16bqYNtE
            5gDlM7gUV6f0zg8WL9+/u8NrsEs0DZERzCkXgXUuxWsEyLpSJj8aEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSkcwQTdFTlk0VDdIckoy
            dFpubGhYTklsQXByaWM2bmlhekZsSnU4aHlBCjN4WGFCaDJudzJsWHJ4QUg3QTF1
            VVdqamxiQmduMjFTZVFuc0NkVXZuUHMKLS0tIGszQ2tHODBJR3dWSThZaHNWWjQ3
            L2RDQUxiSSt1Z0JPOUJWWEZCcjNPd28KkS2w93/uHYF9Y1jodjbtO4lo2W4pGdbn
            vZoyJQqCrXLIJrkK2cJeZ9Ur+jiFM320Wax5hK9KZ8s+Yw0gkMopMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-11-29T15:12:12Z"
    mac: ENC[AES256_GCM,data:E7fbgdW2fME9v1GnOfixNHO9XGmIu2tIG3de0Gpy1W4MQbcPkzHUrPZSQ5tE+3eIm5uAEletC5xnruJ0uYolZyFQZBtAu6MBSbQjH9eMZdjTIBe77C+qnuzWJL4bP7n0Buix6PnnunB7WQuHwoLEPtFXR2nu8DkMy14dHRxO0JM=,iv:GWGsLWP+Dg3FBpDhPQ08AmG9Txa8bwz8eP0jGoLzaFE=,tag:0ybhT7VkEy0WXwYtNN0+2g==,type:str]
    version: 3.11.0
