# Encrypt this file with: sops -e -i pgadmin-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: pgadmin
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2BMImKkwSbUGizv1qyxjmwa+/zbVUm4mSIA=,iv:njKflM8fiwqhDBmC396oyIz+t7gQBlmQ6E5Zyl7HfhA=,tag:pulxbNf9OelHzMyz+f6zdQ==,type:comment]
    email: ENC[AES256_GCM,data:0th44xf2Foe+6Iy0MSQTLDdl6Q==,iv:+jUjgqIeRjNTmiRARPr7eKYShc4O23WkPz1KEWrtHJw=,tag:pjDP5OwomK6JS4mxD13e9g==,type:str]
    password: ENC[AES256_GCM,data:TrLxITBdu8M95Rpc,iv:rrAFPIX/Jbv23O4yw7kYj/S90LrfcoVndS1XwJeUywI=,tag:Cp5WGrQVliwf9KeOtVJVSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxREVqRDRnM1MyU3dtbXNJ
            YUhHUFRSbUNGa2NsQzVxdVVqcmlHU1lMWlVNCkhWM0ZsOWEvamZGaWo1U0hsYlFt
            Kzg4bHRIeGV2VS9Vb0lWK2ErcDIzT2sKLS0tIEpZMkY4eml0bDBPUWVNbjlLRnhv
            a0Y0cFdtZENOMkRMRnNSYlF2a2RMTDQKO3BaZByasQiW0fozOKBAhNyLGoJbie+a
            OxJXH8rWCRwxAPqgb09UxC9JZBG7PtY4JTb1MI5QywF2eSpR9aBA0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRXlzWWJQS0g4Q0JiOFlG
            MElkTC9WZ0ViNTB6Q0NtWTRIZGdETlNyVENvCk9IUmRIL0gvTXlJU0paYzI0K083
            WEp4Z0FHbHZ2aktNOFV4ZkliTDNhQTAKLS0tIG9yUDFKU3J0Rnd2emN4V2hjQ2pL
            VXJSUTgwekFxRnRYU09hSEIvbHQ5T28K3/AvaN2txCBvFwi5uCXmgbkXz0i4M6Qv
            otRnRUelVn/E4rZOUjmYT0MNNIX8416EA+qiOIffoS1Qb2Y8gwd3qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-05T12:17:15Z"
    mac: ENC[AES256_GCM,data:WSushztXB4eObxZzcHctWyn5ewzFmOEnsR7YS98QreZCWFtcmfrMkpn+/JFFVI+XX2xpzRL3SP+JVmiEh+ukCYDgpCW5dFkZ95KOPTKPz4lhKDTssLRzknx8rOOC+fY7kEtCGTNY1PmVrwOo11G23/+p5YEdGXjpeeiS6Zli/RY=,iv:sm3C3cEcipOL0MqDmi0zFYpX5gAVFxNKDv7vkrtdpx4=,tag:Ykk72cJy1AhjTNqPqtOGfA==,type:str]
    version: 3.11.0
