# Encrypt this file with: sops -e -i pgadmin-servers-secret.yaml
# This file pre-configures the PostgreSQL server connection in pgAdmin
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-servers
    namespace: pgadmin
type: Opaque
stringData:
    servers.json: ENC[AES256_GCM,data:+orI3J38OcwB6OOjw+FkK3pJjbTX+mnnQu5GLrxc0MuLEomsR5XmSNQYqztiXN0A1TgX8jlfqSCGgg00aLDEazXErV8WiYA7OfH3g/yI+WIXUpEbAoACds6Lhb8uXpJglhl5SBHrLr4iREgqPzDPuRUgpz2uNJYR4a2y6BS4jLlEkFu7n2k2ekw7ymwFP8mRsP9SjogBUBBGbm4a6epLHGOF57wPK1G15m2CwIQIrG18Vd74cFoale2aYwiS3C0yHx5D4NGSULYoey5PKVNak9WyLhLMQZLEJDKLk78YIfLZCWEGs3Px4k3x3F1nGAJdT+xrPNmrqlD0vql4RTUKbZiJPrlYjtyOtXsyPCz0ulJqvlG+5qddtzWXwX0cGcAU/hs78/N3hErCKcZrhDHNdH0ydqxOXP54SDWP6N5cC/RPrxcQQ9PT0recwwmGMSoq/rE4nLmKa3gEiMxEVUzLOL4vE7/s7ntEOaJ0hxMGYeKVSIxjeqjR6nBUCKJarwnFMlmdIDZZbW6ZaQ5oezaUCwOlzA+1G4aThvIjTYA=,iv:V54GyzilsrEkX5Jqgmk5WtiHQhf7Br/KYtHGmHfBBsw=,tag:zTyu+Uxd/A/2AfbGBxApbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMXpDYy9qN0dwd0huMVhE
            NmpCdlNzKzBEeVRTNUNZMWg0ZlhSU0dIMzI4CkpLaW9ob2dXNXB3MnkrZ1ZFZ1Uw
            K0JINW5IdlRWeDNhOHBIWmlQSTFDNnMKLS0tIDBIbWZvd0RwMVhBL3U4bFFVM1Za
            NGlzYTRhbUhqS0UycUs0SS9XMXNkVkkKGo/pK1ESFZ1QX8j8dPbkRL9ffa/tGXko
            uL27USig29mChG09kt36fN5I4Khcp4TekPa+IEtQhKZzbGZ9i2GZhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaExyL2VuTDB6eDVzTVVN
            YllmYW9CQnd5YW13RzJUTFZvMUxiR2VmSGdRCmVJUHBVRnkxeGE3aFkwMmp4TGM2
            aUFncm5Bc2taTU5UZmJhYlRCb0ZpZDQKLS0tIEd1ZCtIVWNIRlVUNGZWTCtMUkNi
            YlhYeFBZb3d2S05BaGE3eFlEd24zdE0KFZvy8bkb+wGqDD9B2wlmpagRqo7u1Mlg
            x7c/FhO991XX6zXTojCKiBvYRnnlYrKV7qXnSBxVrI17QYToAi0M0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-05T15:06:39Z"
    mac: ENC[AES256_GCM,data:ME/avHaCJWV7bCROkBZAO3rkOxrfGQfTWzErotvApqfYzFl9eanEvR6HC1yyP/q6lKiytokJaO/hdcgrsUmtqOjK+zGB5uDf781xYMVP9yR9JPq1p86Efdtu5v02hGx5UxpMhLYhwDFeWldVN+M78+g3bh37+ANhpq0gi/fSxH4=,iv:qi75YPapBk3AWAyqR5Blqxvh/CaT9bl5rmGlW4Owmro=,tag:FlUhl9os6yLh2Kv1dwd0xA==,type:str]
    version: 3.11.0
