apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secret-refs-check
resources:
  - ../../base/secret-refs-check
  - ntfy-mirror.yaml
patches:
  - path: cronjob-patch.yaml
    target:
      kind: CronJob
      name: secret-refs-check
