apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-servers
    namespace: pgadmin
type: Opaque
stringData:
    servers.json: ENC[AES256_GCM,data:AqtUKJ1bputt7yZMWiCDFZXHKVBmmC9vMhiaR6c6rO6ejdzcfQyKqrheeh274lOGGh45EXHb3Cu9lvpCAvSeFIGljIf0cTYx4HMLoxxdVBy26UvvR57euDuWD9Vh4D0hWdiX/qCCaKeSPFMHP7pLZw2X5Gdlx7OnMwNQ039t9Bn2JLmYjAQ4xvWFsmtg+O6MluyQWhXlZJ9A3nzrTo4CEbFwu3fMASZNtE4GUiKC/T2efbfBD4hC+j/Byb3Y7pZcVKn/CM5+wVWQU08CYk+rHE8801g3DLvmPx7v1H1qO65pz2KjtuOwb8uFtDM6tic5rsYyrg3Y8LgTtcbwTvvA6mKhP6CsDSJNM6EY00TzdBHdgGbQS7KxrrJgS1oChLMvnbpsRYLzKYcniXawRw4/JH0DHVZLW5381GJnAi+n3DbTQD1q5Kz2/vMcAK0YPwXHBA==,iv:WLFGRLgIVtjjSU4T/Dv9+q9jzR4/J2wswhGhWl8gi50=,tag:yL4FawqRCq9VA/7i97b30w==,type:str]
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NWhQNHhVNGNsWmw4TXVF
            QTlSVWhjeENmMFBUN0VjRzlYVHF5eGZLYzIwClZsZWs2WUNCdHJoN09wd3JrbVlY
            TVZZNlRZb3hoSW10Qms3b3ZObHFLM3cKLS0tIHhPRHhEWnRTQmpLQXlmd1U4bXBh
            TzBpdEU4b0RGazd6bkV5Zk5SU282VVUKbZrbu6WI5H7rTlpRcAWwL5ddbVU8fUAq
            DSII7dvkHAr42EOBPAHsKAnJ6Zhq+73dFU+Wm+0TzgFIVI4ole6gbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T15:38:26Z"
    mac: ENC[AES256_GCM,data:atgjAit4YFpEQeDM73fnQEySQGAjnwyaiKi5r7EQlCuEkwq+x2xyI8gb+kSv0iUoJiD92HGKfhtwAq0Su+1+P5ViDKhenVmkZXv0vTyTEqSXS4bknOWZfpXAL9aQa+/I0H4d5vVLNDP2jrZ5JXaenPPZDYgl6patmcGctB8ooBs=,iv:0w+2mrdEuBnlUW4Y9gXUQPY39dquRtPqF95qtRQCAH4=,tag:mLHM4oBPF6mCJZ7aF2QQxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
