apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: pgadmin
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:2d1Sj/FHFLBAHCZ2Q92ijSAUiw==,iv:ov5BbCzydw4B00TPGWOmAiCiJi8N53V/BvX9uRdDklc=,tag:7LMSNCbRXhh1vV6UoRj8gg==,type:str]
    password: ENC[AES256_GCM,data:pL1aGwT7YPkdzQni,iv:xzWkn39EKSOABjJQFgNck/sDE7ZCcZjdgDR1Y5W0W3M=,tag:e23iKcscUPZxQj7UsnvlEg==,type:str]
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MzQ2SXdXQTBxd0w3a3pm
            MGRYZ0xITE9iOHI2bmYrT2JvMldRRHU1WnpNClR1dW1QRURUdnNiWUl5N3puU2xz
            aVdST1VNNlo3ZkM2dDB2ZE9xdHpycmsKLS0tIE5sUklGZE9BeFBldVFqdllUNHB4
            blQxQml1R0NjVi9lbnhSQ25RcnBrYjgKKS3CgMbHsL1QkIZu8pA1ZIBUjZKlKbRq
            yx/6MzZYj8dr/DoSNP/G8pJnKGmLWCkYx0x8dXl5J2cv49oYY9qung==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T15:37:57Z"
    mac: ENC[AES256_GCM,data:0dF6hShZz50oNe+miCNLhPm2KDL2Myjef8LR/s8K+LiRjyrJZ4wT9on6QlGLOooOD6U2o/tj5gcD4Ntr34BoUyEoW+uDHzgkBaOnWr2xRKsDg2bxQEbH6Cg/OBVzmXiorqyvXEuYNgsECKmGLFuQAH/Mxd4Fqj8AqKrEkn/19Nw=,iv:M58RXYdxUaQhkPfA3cY3A4mgtnnIkBwVqG3uL+9Ic1U=,tag:ZnDSDViofigykFo0VJ6LYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
