apiVersion: v1
kind: Secret
metadata:
    name: linkding-db-user
    namespace: linkding
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:dLvr,iv:l8lR9fVpevkjVhoJELspSjHtcomLMegs0g95X6NfPO0=,tag:KMcukBwtmAFSHggLgKwdaQ==,type:str]
    password: ENC[AES256_GCM,data:TJ922csl9rzKD7JQ+Lm22GQ++1ZLyfzo+E3YXGogvf48kZU5BKrzd2GjBzosYA/N8c7npEYyVuKm1dDEC5uepw==,iv:+BR+riN4MNiEZEwq4GG7mAOahKbhs26VwTxiDaoCCJA=,tag:hN3dlw4uKyZCcg7xK1WeCQ==,type:str]
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd3ZrM2xNNXpJY3F6S3lm
            SE5qa09KQ292YXdQcUVra1ptRUViYXlFMVJ3ClRaenJSZDhRd0FUYUw2NlY1VHBF
            RE1wZHl4cHBod1VGdHdXRUNWeS9IcmMKLS0tIHBoN2EyTFFiOEpZTVBDOXBReGZn
            UXlUTEd4YlhaSUN3QmY2bDRJNVlnZ0EKTskomFR5inGeig5AIPAi1/cHIUn1z7Gz
            B/j62GHwSevS7SIq3umrm2Wa1LXMVMqcKhiWMT8RJq8XP2ckSnF6Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T14:03:31Z"
    mac: ENC[AES256_GCM,data:IYOKOs+Hg9gCTRB6EKLOOm8pYedpRZ6OlXIBFNIOcu+/ut8j1NLHjY5xcefy/oc+7gZwLu5W1h6XTLYIHVb9+pQxrw/tLy1BHGOd5B7epfLeeI5FKSMuUyuSyDYBsyZeX0KiQk4UhLFMXX1vYcIw0IWpOmdzdq1MV6IziQK5BIM=,iv:NGnHjGjcCgcBhDskXXmkDUFkgFHgJPYwsKGY+ifmFlM=,tag:Is1t4bRvn/wsRTW2ZSkw6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
