apiVersion: v1
kind: Secret
metadata:
    name: linkding-db-user
    namespace: linkding
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pBJL,iv:m9PzWeBxPMFH/J344SD/L89X96HQsBAoPHtvGfYsDvA=,tag:XWSxJ6eExXCBT+xDqyBcrA==,type:str]
    password: ENC[AES256_GCM,data:dnDPnkcRE4WWDYizow2dVhskqwhj/PabuoQnEv+Ip54I9KWrovlytpBMJiMyr8th4Pe4u7xQsvQzVACxo4e4bw==,iv:tXzZiBJ3BNCle5Xxj39RLS/wXld9jhp+Q6sjoJZGDs0=,tag:BBo7LB2pK2LGOrYPSr8gJg==,type:str]
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S1RvbVZPdXVhWGg3RGMy
            ek1ONTBsVklLczlRaUJMMnQ3MnY0UkR3QlYwCkRmcTJBa0lSMUhkMktDWmFIOHhO
            aEJKRkhXU1lQTkZkUHB1dm5vZ3JORUEKLS0tIHQ1UUNRQ0VoZ3R5RUJzWlZhMk1F
            ZWRnQlpUdFBHR0Q4K3ZFbjI5MFh4azQK9Kh0plpkVyBeGWZ1sWqg6soWGBhNClvW
            ohoX1ZavN49/yrjgTe5rw9GqNYsfohx7f8gAERF3/ttJ3GWuC0HscQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T22:15:47Z"
    mac: ENC[AES256_GCM,data:CyYjs4baL2PC5bjbJtzAwkVO5w1VIBYRdaDisPTxYp3j78GynkZde6FrKy7kf688IJXj8DvrQm//bAFkRuECEfxH0I37/aaIpaUxLZqHWnUU7P2+CPxwQVHPDKfDKpqIbJAQMPXJ3yTyeE/LcDhnBFOL8hpOqSVzmK+sVPTiE/s=,iv:1zGM+KlpjxPDKBUQ6YY7HGwYSNwh2ININbQqc0WYxj4=,tag:xDJ5I3gS6xNfXwC2Cy0fOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
