apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:/0mrf592JjI=,iv:gO4ncxW8zjFK0HOIvYvAxddwCDDo6D5SnwsnkisK6K0=,tag:0Crj0TNYSs7MBZmOLlUzOw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:MiVayMC4ju8mZlIFWg7fdA==,iv:2jH4x85mI8LJ4MrErrloImlEpm2cv9t2XlnRCAXt5Pg=,tag:TtJmT398Yio+oYGASEnn5A==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRnI3N0JES1lCOWlGUlpM
            bkN3NGN4NkdUNEcxMnV2V1pEZDN4NG1UN3lnCjNkNXYyUjcySDBIRnpmMnJ5bk4r
            SDBTNGNRRWF0NkRYNGl3ZENMWnVCa3MKLS0tIEJDM0hITm9Za3RJVDdCTk9FS29Y
            UHpDaFR3ZFF3RFlvSDlweVlUVktYSGsKMyUxO3dDqhQmA4mVqv5gzjydUz0nh9oR
            hblfWypvhiYuDFzbPUzWyAhKlikU+B9pNe/BHv6iMwrlFmISAz89HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T15:12:26Z"
    mac: ENC[AES256_GCM,data:8cgRPQEKKIfFpapqKETMeSB06An2jRk8a7wL/kasq8LmZaGahsXXKaZ1bEHodKyZrDc0/e0s580v4K5zsz4DIm16za2Mr9b0iOoeSK3WGs2KiiNszWPT2Z3aQcwvsrVHK43I72PMR8khTlj1t+6XHWp1bWz1SNv1b5VJrsAy9Ec=,iv:vIIN2GyDtvwZRpyv8PiueQTez3FTo1DtOz1ZrughowU=,tag:4yvXTVqua/PBwRIj5fv31A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
