apiVersion: v1
kind: Secret
metadata:
    name: renovate-container-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:5YdxhCc9mffgDtdhYCL2x8hSY3sURbB6sn87hxORx8JcAGmWTqAGhZ+fLJMaVyphkYIk8iwM8VOQP8OIj2CqnG8wj6qJePrbdg6cWq7Npxgph6wUSfbetJ3ioiwl,iv:5T8goeqGsyem89Aevq/BHlZHmE11rOEx0GpDc/4v0EY=,tag:oEjYwdvbOTinsivwu7DE3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZmtwMlFobTRWLzhKYW5m
            TjFINGxIOUtxdFJVT3hUVXFiZ0FmNnBSbWxFCjZ2d2krKzV5ZC9id2JBNHJWYTB1
            RUNZZEpVREpPVWhMbW16eFRiTnA5NDgKLS0tIG9HeG03OUpVNlNLR291NHJETHRr
            M0JWMTMwU1R4dnNIRTdvRmhBQTE2WEkK2mmrDF++mJA+kuEgun7r3on3XK5X+6UV
            brS1tULmsWSaL8dtwRlZmcd3qYCDBd79Xb5/fABGdi24CFhzIM/m9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T13:01:56Z"
    mac: ENC[AES256_GCM,data:6LsWoH6gyGq+0uZP9QIu3GTe4cRo4AQ1I/qAQ8nS5ED+2J0gCJft1OgWEtfyXChmO8KBfvC8SKKgHFxe1mGDFrA+LgVIgK+K1fcymjlh/t04Ns+dEtfkehUY4RM1Sn6Pbbr9ZpzaBPWwSPrk05BcL5ZzYwg1mjI9mJofOv/6JSE=,iv:skHcEF48Z1XPbcIHC+3lOipPVr0chMN2DXm4G0mufPA=,tag:YigivUvUdlo3UTzX006eRA==,type:str]
    version: 3.13.3
