# Django SECRET_KEY. Signs session cookies and CSRF tokens, so rotating it logs
# everyone out; losing it does the same.
apiVersion: v1
kind: Secret
metadata:
    name: tandoor-secret
    namespace: tandoor
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:KVXXCIohSayNbcTWPALwsYWQwIo9lCb47l9hwiqV8cXxs8QTcdw0Y+wYrm8JJlnxuTo=,iv:kigSn4PKu4CFZALvd2WKoZPzDmLeP/oQpZmoru7wSzA=,tag:SLdpw37tZrAyI40AoYVOQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTGRaWUtCYXpoQTR0bk5a
            SVMwSzBNWWRKYUIzcDRzN3NibFVjM0NYdWkwCm04VjVKMnZRdnJvREoyTXN1eTc4
            bnR5TGREdUoxZ2hyRUs2NHZwTnZlSUEKLS0tIEdMWVhQc1QybERnUE0wQm41U28r
            aitlUkw4OE15RkJIa2h5ODFmd2FTS1kKmHfph0bqTlLebMCdccXqJbs5Iud81FuE
            pxZxhao30P91HBmZmHpT3rsfYAnOCEBM9Q1k97Rp/W07c3YYq33ypA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T22:08:50Z"
    mac: ENC[AES256_GCM,data:fbKo42d8dV7YovH6bq1VPswVeCxetO8xhVVRsQMYG5zbz0ZliChTaeuLal1J3GuYRajJuGTpBr3z4HWj3iCcbqxU/HRE9EwNtu/weNiup7rmaf/ikKHt2ZQ0O8WWrWCDa1jsrF9hq/tCEFQdlZnHD/FQa/b7uGUFefuq5UDTvBo=,iv:rRoD7haJ+3q37ip5siRF71IC8hww3zCuaLIyduYVYTI=,tag:Zvx3cpWbcgLi9uRBaSBiuA==,type:str]
    version: 3.13.3
