apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/recovery-source-check
  - ntfy-mirror.yaml
patches:
  - path: cronjob-patch.yaml
    target:
      kind: CronJob
      name: recovery-source-check
