apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatus
  namespace: gatus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: gatus
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
