apiVersion: v1
kind: Secret
metadata:
    name: b2-credentials
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:sDauquygYkZvwCFyqh/UxN72i6exOlJkew==,iv:eeprjmvtwZYPlcJqLstv66c6grZj2ty1cf+pfT5uubM=,tag:XqguaED0wH7K3bbXmUCnsA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:RriXphqqMgMoAgopIbeGkdDkWSyqqGglnBhKgdx8NQ==,iv:ZxiHm6SoI9zbjE6l/I9sKQgC62SEgwKYOngf/n7EEVI=,tag:k+Qrb8dGzCoJMpQwnm8x9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUUx0cFQyWFlPMm1pMk96
            OTFzVkcyazVZWEhxb2ZDTnlYaVZOSGdLU2hzCndYelU2VXhhVnQvZ01mZlN4YW1v
            L1hQQjhuTXNMTjBQeDR0UmRFQ3ZuYUEKLS0tIEhLSlM2dHdmaVFyQmI2ZnMyUFR5
            T29FaEcrWEJqWjFxbXZWcUhlRkZRV3MKz6dHAVinZgkUV6xn1CWc5d5mtWwzjQs2
            kRNcACn+cPgFFpQWxKguhJGvqlg4asqT91YJQ9gcA5h2eEcH4F2oqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWXhaUmJlMmx6em9OcWJt
            SWh6NFBpNVY1eEZyM3I1alpMQjk5SkFCZlNZCkhRVWpwNjdsclNnOVJVdEVTYTZF
            THdnbFNEaXZ2WUx5cEJGekk5UVZCQWsKLS0tIHJZNUs2RXJIczd1OC83NzUzZ3Zq
            NUxHc0tyUHZ6UkFJcHRHOXI3VnpRUmcKFTnc6tqrEh/PshSUMvf5xsm2dpxZXicm
            RIjRIUNBOmj+qbdMWDrv6qboesibEtl3apds9DSmyCdkZPbvbsFULA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age146l4mqkpljck0n9gfncn2te3yqu0s25xyn3438j2pfmg0u4zju2s6fyvrv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-03T22:42:01Z"
    mac: ENC[AES256_GCM,data:e1aEbyDhYZyHJf6KhIXLbqUqLOrQMshRVLlxaQMzMzvqQD+JJuP8epx62w0yHQZWzocTzfOK1jUCMIAuyVU/toy3S6dAJyqEEbaG2CwNUZ1S5Ifkrxl498TO311MxrtxY4qWmLRUgn+ggYKz6uQje3nNJTFJp6JRmRApcrZWgWQ=,iv:+nFx6mNy5jkHNQjIFr6pH9imiF8xNUVg4S/cklecSLY=,tag:ZHGXbaNdCua/4eP0+letwQ==,type:str]
    version: 3.11.0
