apiVersion: v1
kind: Secret
metadata:
    name: pg-role-commafeed
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:wI1+IG4L7TKM,iv:v1oozDqjL8rW3TI5jKlCL8sRo7qh25P/iGSxSaWtZl4=,tag:SZ0i+bLp5P4bvLAY7NfOPQ==,type:str]
    password: ENC[AES256_GCM,data:grtrzVmdRH2SWVRP35YOGar/rH9M0dnnIedMWu29Adw=,iv:mp77uYMyw4dz7p3JeUsCOPrjBqrIGi3Vo4jS94ldyWs=,tag:VltxXam6D4ibuHqAkGimEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd2xoVzR3cnFDd05scTdy
            N2wzU2FBcjRzSCtkQXp3cndMNFJKZHA1Q1YwCnNTcEVydUp3Nm1YSzhiZkNTV3Nt
            cjBXU0hFZFRVNlZTK0NtRk0zWVpaS0EKLS0tIG9iRjhKSEplOWFzZXo1bW4wS3Yv
            bUlHV3NNQWRLVTNSZXo2UC9nMHVrV1kKKW/WvnhVzJrVUEydIoWqw1P4Vyvc1HLO
            rM3vh9RF8IYKsNm6iBaONMOoyAlsMlkv0bR3l1pXh8HB3fL4Id2bNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:DM4VO7wtwZ26YVUbninzMw42ZISmbMLMijHrE0Z2E9CIS2JIGtcApILz8rTJpqDx8EXVqzSaG/8zkBk2D0n7YoTfxew4usS05Pmm74YBGqhAUsiZOkhgmP2K3k/f0TnPnafWi+bEfhCa2lpTEGlIm3zJSBQ34w6ZHwcniUQcZ7E=,iv:9K7U2UVwnXEhPQQiSPyhfi+WNZCftTC5DgfX7QlKq0I=,tag:ZPJgkNppHOW4TWDanpHuSA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-linkding
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:z/OX11FUQdY=,iv:NDkCuoUtcI8oFt5gg7guCbcJwKGDP6TXlS8xBlD50wk=,tag:5OoFqBp/2YSU3UXoVEPXXQ==,type:str]
    password: ENC[AES256_GCM,data:T51OX+NRJgOE+3a+Dpa1GcfGGhkqbkBsfAzqWHSTc8M=,iv:cipyfKqzIcqpr/KJmqWqAKFJw+Y6LIGjeZzjQuM9NI8=,tag:9O11Aw4vf+JPDMk53Bpjtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd2xoVzR3cnFDd05scTdy
            N2wzU2FBcjRzSCtkQXp3cndMNFJKZHA1Q1YwCnNTcEVydUp3Nm1YSzhiZkNTV3Nt
            cjBXU0hFZFRVNlZTK0NtRk0zWVpaS0EKLS0tIG9iRjhKSEplOWFzZXo1bW4wS3Yv
            bUlHV3NNQWRLVTNSZXo2UC9nMHVrV1kKKW/WvnhVzJrVUEydIoWqw1P4Vyvc1HLO
            rM3vh9RF8IYKsNm6iBaONMOoyAlsMlkv0bR3l1pXh8HB3fL4Id2bNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:DM4VO7wtwZ26YVUbninzMw42ZISmbMLMijHrE0Z2E9CIS2JIGtcApILz8rTJpqDx8EXVqzSaG/8zkBk2D0n7YoTfxew4usS05Pmm74YBGqhAUsiZOkhgmP2K3k/f0TnPnafWi+bEfhCa2lpTEGlIm3zJSBQ34w6ZHwcniUQcZ7E=,iv:9K7U2UVwnXEhPQQiSPyhfi+WNZCftTC5DgfX7QlKq0I=,tag:ZPJgkNppHOW4TWDanpHuSA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-tandoor
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1Zlj1vhygw==,iv:qv/vLHm8C9PeHpVeT0pf5GlzvuCWNwqN40+VGMWI/nA=,tag:V+DTz+dBgh1K/fO5auYDMg==,type:str]
    password: ENC[AES256_GCM,data:5lvM0setwOV0A/oe10BCxP0pQSgykCog2H88abfcg7Q=,iv:pgx7GQJXZURkZm6bk35DLSOCXe+d/mkD/Cyc9E5ZsHg=,tag:xbe6NetVwb4KsoiAk35ncw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd2xoVzR3cnFDd05scTdy
            N2wzU2FBcjRzSCtkQXp3cndMNFJKZHA1Q1YwCnNTcEVydUp3Nm1YSzhiZkNTV3Nt
            cjBXU0hFZFRVNlZTK0NtRk0zWVpaS0EKLS0tIG9iRjhKSEplOWFzZXo1bW4wS3Yv
            bUlHV3NNQWRLVTNSZXo2UC9nMHVrV1kKKW/WvnhVzJrVUEydIoWqw1P4Vyvc1HLO
            rM3vh9RF8IYKsNm6iBaONMOoyAlsMlkv0bR3l1pXh8HB3fL4Id2bNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:DM4VO7wtwZ26YVUbninzMw42ZISmbMLMijHrE0Z2E9CIS2JIGtcApILz8rTJpqDx8EXVqzSaG/8zkBk2D0n7YoTfxew4usS05Pmm74YBGqhAUsiZOkhgmP2K3k/f0TnPnafWi+bEfhCa2lpTEGlIm3zJSBQ34w6ZHwcniUQcZ7E=,iv:9K7U2UVwnXEhPQQiSPyhfi+WNZCftTC5DgfX7QlKq0I=,tag:ZPJgkNppHOW4TWDanpHuSA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-gatus
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:SWsHVQU=,iv:YmFnhxWUH4XlJF9LXXsBkyJPIMMbfQl90J7gvRBOFOg=,tag:L0IBdmxDxjndpNCS9sMAug==,type:str]
    password: ENC[AES256_GCM,data:FT9zeHEGoAy1DWk3f3or0CZmTp5pUpIWcZwjwsDFfUQ=,iv:dAT5FihDztFIHwt+qSrvflyXd8npYKZ/K62PAq7zczI=,tag:Vd6N3r4P7Rl072PTxBrjVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd2xoVzR3cnFDd05scTdy
            N2wzU2FBcjRzSCtkQXp3cndMNFJKZHA1Q1YwCnNTcEVydUp3Nm1YSzhiZkNTV3Nt
            cjBXU0hFZFRVNlZTK0NtRk0zWVpaS0EKLS0tIG9iRjhKSEplOWFzZXo1bW4wS3Yv
            bUlHV3NNQWRLVTNSZXo2UC9nMHVrV1kKKW/WvnhVzJrVUEydIoWqw1P4Vyvc1HLO
            rM3vh9RF8IYKsNm6iBaONMOoyAlsMlkv0bR3l1pXh8HB3fL4Id2bNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:DM4VO7wtwZ26YVUbninzMw42ZISmbMLMijHrE0Z2E9CIS2JIGtcApILz8rTJpqDx8EXVqzSaG/8zkBk2D0n7YoTfxew4usS05Pmm74YBGqhAUsiZOkhgmP2K3k/f0TnPnafWi+bEfhCa2lpTEGlIm3zJSBQ34w6ZHwcniUQcZ7E=,iv:9K7U2UVwnXEhPQQiSPyhfi+WNZCftTC5DgfX7QlKq0I=,tag:ZPJgkNppHOW4TWDanpHuSA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-nightscout
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kif3i8v+AMzPSA==,iv:HA8CVg0p8C6DXeLzGQ/EkHnaDEc6NcObSL3sQ4CcNQI=,tag:0HYVuLBIOnWRi0FBPz0Bog==,type:str]
    password: ENC[AES256_GCM,data:FSKytj+Q9UnWzZQdsJVBIua1eNcLN9GVnvwCILPdhkY=,iv:ybEh+/j0ugKeWDPijwa/E21l6vgfiXvMjF5NFDNLzHw=,tag:tSXqOYT8L9VvwOMTAW8xJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd2xoVzR3cnFDd05scTdy
            N2wzU2FBcjRzSCtkQXp3cndMNFJKZHA1Q1YwCnNTcEVydUp3Nm1YSzhiZkNTV3Nt
            cjBXU0hFZFRVNlZTK0NtRk0zWVpaS0EKLS0tIG9iRjhKSEplOWFzZXo1bW4wS3Yv
            bUlHV3NNQWRLVTNSZXo2UC9nMHVrV1kKKW/WvnhVzJrVUEydIoWqw1P4Vyvc1HLO
            rM3vh9RF8IYKsNm6iBaONMOoyAlsMlkv0bR3l1pXh8HB3fL4Id2bNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:DM4VO7wtwZ26YVUbninzMw42ZISmbMLMijHrE0Z2E9CIS2JIGtcApILz8rTJpqDx8EXVqzSaG/8zkBk2D0n7YoTfxew4usS05Pmm74YBGqhAUsiZOkhgmP2K3k/f0TnPnafWi+bEfhCa2lpTEGlIm3zJSBQ34w6ZHwcniUQcZ7E=,iv:9K7U2UVwnXEhPQQiSPyhfi+WNZCftTC5DgfX7QlKq0I=,tag:ZPJgkNppHOW4TWDanpHuSA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-authentik
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:47nTTTtHbDi1,iv:ibAkNyzxrXDWzAF1YoQQsRnKjD7EAroKc5LH4nCndkQ=,tag:x6/i5cD5cVzHm/DdicS+rg==,type:str]
    password: ENC[AES256_GCM,data:T2RTqs0IuuKPO23hjRkkVNxqADND0XWsEoWKBRJ/RVw=,iv:pWPdD7gxX5f9lzlXyPSLRn8qqbxrhnN8QXhmlekpkwU=,tag:vaPcY3UKpdY2jnum3yWSFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd2xoVzR3cnFDd05scTdy
            N2wzU2FBcjRzSCtkQXp3cndMNFJKZHA1Q1YwCnNTcEVydUp3Nm1YSzhiZkNTV3Nt
            cjBXU0hFZFRVNlZTK0NtRk0zWVpaS0EKLS0tIG9iRjhKSEplOWFzZXo1bW4wS3Yv
            bUlHV3NNQWRLVTNSZXo2UC9nMHVrV1kKKW/WvnhVzJrVUEydIoWqw1P4Vyvc1HLO
            rM3vh9RF8IYKsNm6iBaONMOoyAlsMlkv0bR3l1pXh8HB3fL4Id2bNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:DM4VO7wtwZ26YVUbninzMw42ZISmbMLMijHrE0Z2E9CIS2JIGtcApILz8rTJpqDx8EXVqzSaG/8zkBk2D0n7YoTfxew4usS05Pmm74YBGqhAUsiZOkhgmP2K3k/f0TnPnafWi+bEfhCa2lpTEGlIm3zJSBQ34w6ZHwcniUQcZ7E=,iv:9K7U2UVwnXEhPQQiSPyhfi+WNZCftTC5DgfX7QlKq0I=,tag:ZPJgkNppHOW4TWDanpHuSA==,type:str]
    version: 3.13.3
