apiVersion: v1
kind: Secret
metadata:
    name: pg-role-squirrel
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xRapwHbOm8I=,iv:tkfEJ6Lk2EZ2zNBJMK2ybdkORJBWwwkjf5Hifd0CJuI=,tag:OZmOg19y/pjdQSBxI8fkzg==,type:str]
    password: ENC[AES256_GCM,data:xeuH7SGHT4wqEvPBR4gJs4Y6FZq7mMZOD6jMgw==,iv:vaerbL2zGyrZlt09adECtY3UC5yLUuG2NHnGJ1INFIE=,tag:WICPpA4h31/lyIClaMk7IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQ01PQ2VVanFkRzVIOUsz
            U2ovQnZTZTVZS0tWSll2TFZyZkJDTUpSaUFVCm5aR1pCNFJMcEZXT092VTQvVDlI
            SVFRR09vLy9NUzQyRlJRZkM3OTBjM2sKLS0tIEVFU1dvTUxXbnZnM210dTdQa2xN
            T3lvRFdUWGFGUjNGZnVYM3NBTTMvZ3cKq0F0dcbpwl5D2+b6oVVKAELvTw9uIPko
            vxCQw/T+4Ng697Ap6DIygMPAIdsPZLiIC723YKpns2JrphfjrBZfwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T22:58:29Z"
    mac: ENC[AES256_GCM,data:n2+x29rylxDU5ob2MP6ZydzW9UMo9VVsthGasMvgJAr+OdCs3sK6fi0xacIYv2OSGE0KK4m2jtcbc52HO5kRTpUM/PCH+GO2DNa52xRhwzlmUogfm8StK410lJVBNtpLhFjMPkSYheJhYI/+YtYNPyDo+Y1OtHHsQYxT+Si+uRo=,iv:3hvdMXUGVmco22bRCEZZUgLMpFQ+KKOL8khLExyv1J4=,tag:JJLSTuNX8XN5KWwVhWTNdQ==,type:str]
    version: 3.13.3
