apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - cloudflared
  - commafeed
  - gatus
  - homepage
  - immich
  - linkding
  - mealie
  - nightscout
  - ntfy
  - pgadmin
  - speedtest
  - tandoor
  - netpol-check
