apiVersion: v1
data:
  API_KEY: ENC[AES256_GCM,data:BsurLZAVG4trw9P4g65GGTsFUbObbDaUxDfoz66nXtw5Pba90lo5fKKgXAoSN6XEOhFrSUqL8wkNPYJt4Nt6klgcTJ8=,iv:tx93vdQeX/R5h0mgJ+0ybiIdavnjefcymj7q087JLEE=,tag:Zf/i7EtAdpfq2Q3VCkT1Qw==,type:str]
kind: Secret
metadata:
  name: speedtest-env
sops:
  age:
    - recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWmduZ3dXRm50SENldnNS
        aTVOVkM4bXJROHh3eHk2U0R5QnZLK1ZWSmc4ClluU3MvbURLcTM4eGJoU1dTMWVq
        UDVrQWh0d1VZUVNSTzJ0TVRnbVFlZVkKLS0tIEo1OWxOVUNYWElMZ3RvcndCVlM3
        dGlSVjVQTFNuaTd1dE5kc1VJcFdseGcKWg3+wA77nFiNqzGJKHImmTnGqFn4RVkV
        hJd1bwH0O02CgApE5eUUZqMFXP/cH/DlgDlMkVGdfNTlOmqbEXkxKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T21:33:02Z"
  mac: ENC[AES256_GCM,data:NG6EqtVB5iMQ1VSmwE4OdTg22M0cvospQTt5trknXkhtZUYf8GkVBZB9eudQxTZxHD3Bedu3fiI9LlBWcEKv2F4cTYnihrE1zcUM1PCF4d4lWuwkKYH9K9kaaW5Q6AyOqg73zq+ouSQvRWkPJwss10zME3A0ZdKm7GOk8cWjHVA=,iv:+jfAWSfds1ePRulmObCGuJUD4jgEor9Ccy1cs7i2Pf8=,tag:TPsqjAn9GGuVPjeuhBu2aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
