apiVersion: v1
data:
    API_KEY: ENC[AES256_GCM,data:BsurLZAVG4trw9P4g65GGTsFUbObbDaUxDfoz66nXtw5Pba90lo5fKKgXAoSN6XEOhFrSUqL8wkNPYJt4Nt6klgcTJ8=,iv:tx93vdQeX/R5h0mgJ+0ybiIdavnjefcymj7q087JLEE=,tag:Zf/i7EtAdpfq2Q3VCkT1Qw==,type:str]
kind: Secret
metadata:
    name: speedtest-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN1dEa0pZWmM1UlBzWXhV
            QnlUNXhjVFBWWURjNThUcEptbmN0VCsyL2tjCk5NckVPc0U1YUhMZ3IzYUlUK01z
            aWNheDYyRS91YUVpQWhLSGIyME5pZDAKLS0tIFpOV3NadnNVSTZ2Mk8rS1JjcUww
            a1JKSmRQWXhpSFZxRzFLdzhQYkoyOXMKJpfmI2/NuhlCBb9wOBzNaw4+gDOkcc/9
            Koe+5uWrQ5LbWOwbjqYGs8NvuNczzB0FznQmkQGQHuLto7o4wiAiDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZXhJcHA2SVE5VGF0eUxB
            YkxuZHAzbTl4L2UzRWZzaEtYeWxBZm84YzBBCjc1VTRlQ1ZNK1lDdHJJSUVVM0Z0
            UXV4UVI2cnFCZDl6QklKK2RReDhYdVkKLS0tIHlhQUJwem05RTh3cTd2YU54UGFu
            enVHUU5yWUdqSXRXc1FkcEhYQzhHZkkK9xukcsmoVfKQtjPxNnCfrlyFjHbYWp40
            MYh7lKJQpb3fkjUHaKi6cBvihqlYc/7BAguSMDnFAwYMXVHnSSZ1zQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-06T21:33:02Z"
    mac: ENC[AES256_GCM,data:NG6EqtVB5iMQ1VSmwE4OdTg22M0cvospQTt5trknXkhtZUYf8GkVBZB9eudQxTZxHD3Bedu3fiI9LlBWcEKv2F4cTYnihrE1zcUM1PCF4d4lWuwkKYH9K9kaaW5Q6AyOqg73zq+ouSQvRWkPJwss10zME3A0ZdKm7GOk8cWjHVA=,iv:+jfAWSfds1ePRulmObCGuJUD4jgEor9Ccy1cs7i2Pf8=,tag:TPsqjAn9GGuVPjeuhBu2aw==,type:str]
    version: 3.11.0
