apiVersion: v1
kind: Secret
metadata:
    name: homepage-env
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:08hrUDOI,iv:qqA0UpYzNXgBnvItdN89ueASzdMO2/klGppCPkqOSq0=,tag:4OjPHdh31m2O13mxh/qmvA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:fcqNkxs=,iv:C84VCJGWKEihaSrfFetw3KwFP+wOjRrvOxD4zSIIWbs=,tag:G+3rHz+o6VGKtbQbVj/I8Q==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:/X7EbwVJpqlMarqCpxnFyo4unNCd+h2CA3bNeFUbWSOn0jL3SdXBig==,iv:mXjAiyFuUoU3a7o1MLRY6a6hol58iKJmDKFA3lclqBk=,tag:i3Ftv6QxJdLhT8b3iypiPw==,type:str]
    HOMEPAGE_VAR_MIKROTIK_PASSWORD: ENC[AES256_GCM,data:eNjv8Zm//fBqSzyu,iv:KGfqb9QQzi9zwUyUBMNhN29LGawOBSdxxvc2oYgBCzI=,tag:mn9c1nt2n+x0p2nXwWxsqw==,type:str]
    HOMEPAGE_VAR_MIKROTIK_USERNAME: ENC[AES256_GCM,data:E9ACl78=,iv:84sRpujPwmpRoS08UkifOC/BPjz7FGj8GfBbHZfWtwI=,tag:0zoDbFjEOwq2SYEOXH+hCQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:MhQVKY0xNa9laLImLC6hODlBAwjGJh10nQXa+R8zwlvPXilX,iv:3PawNUfhntCUel5gjzFlBJCQo4PLV+sXLPIYXEGJn4o=,tag:ZbTtp5c+z43Whh+D5xxKZQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:JjuTOUiKK7Oub63I5MPiYw==,iv:gj3fIm7P7KUzTatGHe6Uosb6IqzzTxlkfzLiMHRv6xQ=,tag:vOs4wRrijyuVug3vTdDQTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRzkzeXpoUmE3RC9tM2sy
            cDlnd0dtZWZzNVRqMTFxQ3RsUVBXNUVwdERnCjNNbExicUF4SVdzUERLSTNUUmM2
            WXZHN1NhbTJpM2llU0RyVWd2L2xBNmcKLS0tIEpJZmtlOTNVcGVVYk83TEFUcVNQ
            TjR3V0VJaUhqZmlZakhGNm83RFZhZ1EKG63Ij66WQgs8V/kuUl3iv+ZZoi9VuVEd
            AvZqd0N1S4e3lNdgZX4nUfHKwb5TuKdGYMsXftZQgAs86UkFXMkGdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T10:25:46Z"
    mac: ENC[AES256_GCM,data:/xWuYXS0wP6eB8Hllw6LhNPgI9dANKabOvBC8FEmvFlEusjglKMch2DaCmPLe8Dr+hMaiGi0NgXBwBi8/8X3WCwsuLDFwB+QFvum/GMb8e08B/Gl5jhc0ahEuDWyRPKfAokOVa/uix5pOjxXpNwDsiZTWMfyNjSc1tmVOcPY5Ms=,iv:XfaQG+prT0DtsSa/MqtvfyZkEDAPSP4BzOHqjQY0IS0=,tag:0tIhCCoeZ71LYMEMcCnLUA==,type:str]
    version: 3.13.3
