apiVersion: v1
kind: Secret
metadata:
    name: homepage-env
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:7VfVF5BBWHKiID/nCf99RNH2U9CWbaPYHQx+xb94dTOwkWfZkXf5wNrJDiIWwJ5siEzUUiPBY4aA1eQD,iv:c2/M/YlV3AXgYVNqI81W7i3ohtJh0z9YH8XhAO3rsag=,tag:i7JWKSCJGaVsLwki9pciAQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:x8osiwXYizIR9IwRawMlCHFCUqJVDSXfrZPxfg==,iv:rUx4bO5Q5VSRqaUNRdLi5XpTmE8nogG5SurfnP0e8eg=,tag:i1ROeAJsLswO+guizLEL8Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:5UEMBf0=,iv:PgDFEYmH+Lz0DuGYDNyaweN2rHXJXgoBuPnu+gsaAi0=,tag:iO64e+MUeiQKE9WKrBRkiw==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:yOOHYJuNqxpdfJpAorGZvurNnkEtD3WI5lR62Si6eJ/El3gdP5GVDA==,iv:mF48s2miTO6dMm8Anbpsj7ocRICGBXTt0kQCb0sAIfI=,tag:DB/TGx2P8V57rdP2/3oc2Q==,type:str]
    HOMEPAGE_VAR_MIKROTIK_PASSWORD: ENC[AES256_GCM,data:saxktmj42gJtabud,iv:WvZgA85JDcdTJbn/wa7J7X8uygiexoZafnmPScGOCMw=,tag:Dbl7SLtoJ8gBQw95SSqpGg==,type:str]
    HOMEPAGE_VAR_MIKROTIK_USERNAME: ENC[AES256_GCM,data:YE4pD04=,iv:AZd2O1u4oKr7KKjHLJFpzOUigm1jcVZNCTSvSp66KdY=,tag:/jTq+UccPeZlB+fe3bQv+Q==,type:str]
    HOMEPAGE_VAR_NTFY_PASSWORD: ENC[AES256_GCM,data:1ZHxY87MY8TrtPvWPSOcxUDGCEzC8Jk0LvzxGhhVHCk=,iv:wwSjqelXYutb60H2uXssQa5NR9M6TlP3S+UqDlEt6cw=,tag:/7loE+kxOZuFPPcKooZPwg==,type:str]
    HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:qzn/Pag9JkePweRiKaF9AJg31nSsbGxKORMK9zrDQ26YCMVR,iv:puVVid63xu+74Utgf0d8VjIbUwluPRSnqb3j4Hpy2DI=,tag:W0zZyB5Bm36ghSUufW7Ilw==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:qhrviU1diy5yk/oJgFeFTA==,iv:1PmhAe6ezcOcKU3ZVdXFiRH4Em1HrFJegMGjpdzBZ18=,tag:YbGoPSEZyJAJHpHztEPA2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudEdLOUM1U05JMzU3bWVE
            WjFEdUxTNnVEYmFRSzRrQUJ2bG41b3crMVhrCndIQ3hydHJHYUZ1OTJjY3ZjSmZ3
            ZGl0dW93VkpCdmJ5dlN1QTlQSklrTDAKLS0tIFkzc3ZKdWFqb3k5cTV4UkhMdVRx
            ZGgyZ2YyM3ZZWVgzTDhXbGdYcjBhTHcKPs2vklZP8nE7v386rLd7Ot5AXjUpnyUG
            QWNi4UQp0Sr14gSZ5Ac4laq8QEY2Emgqptmu4XQdvIBb9SNrjgvlwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T17:48:14Z"
    mac: ENC[AES256_GCM,data:A+B3f9e8t1P2idvKk97z4EsmpG9oWyAcfTXgptdNIPeTAQLUvd6I4vNl2XgmPxovbmg5mvCJMXMxepSQhOsABfvhvOhdkC3Qmy1a2+9NmdSy63ZuWdaZjzEp1BQmnn8mIoti4Guee14IODVGwmgkOPDp/InWAviU9kvYtvWi32s=,iv:KmQS+L08jqwewWEzb4Y09+rtZSwMSRPr5ImfizIdahw=,tag:CNlrA9Fr6tKkfe7l/cmdnw==,type:str]
    version: 3.13.3
