apiVersion: v1
kind: Secret
metadata:
    name: homepage-env
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:FJHiTjbSCw6HVJvYlK27BzST97oInNhHCNFKyA==,iv:mSMud/ZHK7D+msYlf03OA1qzRTYUNhkeysm7jFmdRQQ=,tag:RBEQsp9PLBUrq2EP04Wb+Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:Uc+cqhQ=,iv:GL5rzPfD0flwNF9S9ifCgB/afRXNXVVq5Psl1gq9VgE=,tag:qZoOkWqfbYSu1hxgpOkDyw==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:5oyW8MiBKQPFCycuSQk0ntny58aFQlFKJi6CcfCz700RRt/q9y4IiQ==,iv:ZyGSW2eWyg251grsCyzF/WRePtpxSjd6iuz7snt8j2g=,tag:Bji1IK8i0EqTtp16Zv55tg==,type:str]
    HOMEPAGE_VAR_MIKROTIK_PASSWORD: ENC[AES256_GCM,data:eD8dbA0F9NzgdtMq,iv:ZkUkWaeZ4FwMRSopDs3g7h/qSEZ5+uodCYjanTqM4hY=,tag:0rNa3BGgscnTZVCWMZlzJw==,type:str]
    HOMEPAGE_VAR_MIKROTIK_USERNAME: ENC[AES256_GCM,data:VmvbCGo=,iv:W2HMl5GFObkSBV80RK52Dkg5ma+08VquZwJ2A6RfD/w=,tag:1kcd5euWYIMeZ83himujdA==,type:str]
    HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:jNxVXAvhD/5zS3eRPg7NkLLSQtaY7kG0aO+NfqCEzerSx+Me,iv:t+oi+TamzjPdS8LBZtfit/4FGbBjpCY9TFF7PyqfXJI=,tag:mk6i6CLe3FK6gcp1ZkGQEA==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:Em0wqC5FUN1cfFd7iyIR4Q==,iv:Ibpq8FARmTYKRgLI5+e7faEL8PL2g+UvfakGTmZ0T2k=,tag:tI2XxomNFNqFzE6A6qAOyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb0JGREordjRjMnJIQkEv
            K0FQbEpnZFpaWXY5b3EyV21jeURIM3AvMHcwCjBXU0orcmg0UnBUK0pOUUsxejRL
            WU9iRFhWMzRlNlRsZVZ5M3MvQTJad3cKLS0tIEVmdjk4eHJPcnpBdVBnOFYvaTBn
            dzNvMnQ3UkVxZ0JNbUpXU0ZvSkJIQlkKsKqAoNtcd5Icgy4JwE5+iYcOEvgAs4Kn
            FnRumxidrGEtuZNZGJYWs9pTrMtFtk9a6tu9MMD/ArY9A8+7GEaduA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T12:14:59Z"
    mac: ENC[AES256_GCM,data:5d+UlRGlC3anbNOwLP1eY3cikiQ8MnGDBBL46bXQnhxWH5EGAdXZ41lhBEP9Atg64U6pMLsyKzUF7afMmUZ/1KDXFIVilxzkZQvD+d/tCDQPr4T1dJ1HMGLc4swlXUQkuXfdXccLCZu+Y7PuDTZD1lT8Tzg+2hYF6iz96b2nQ4M=,iv:16810vcw6W3pBAObxfNDQzbWtf/0sXyw4nCiuMwLkig=,tag:gR1mQJYHL4PyWTSvn/XZtw==,type:str]
    version: 3.13.3
