apiVersion: v1
kind: Secret
metadata:
    name: ferretdb-postgres-secret
    namespace: nightscout
type: Opaque
stringData:
    FERRETDB_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:6iydY9QWAnz6iYpXk6ap5Cwb7c2hNFGhrQ8ahu29mHLJAn1n7+vB7S5Y6Pm5GefcgJeKt6OZhLaWiXv+6xbA5A==,iv:pzdEkOvd69moxA9c3IEC5aOWvBeEzIOEskmBpNpQlHo=,tag:ufDt6mblkdFBMfabipMGug==,type:str]
sops:
    age:
        - recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRHdpK3c0Wlc2cVRlQjFN
            OXBQQ3FHR3hpaVplWnhmSWp0Z1hkOTNvUVhnCjF3aE4xNEN3VW5tV1lLb0lha05k
            R0l1WnMvWTlYL1oyRENTWm1BQVdUUmMKLS0tIEs0Smx5ZWRDMEpKa0pDdkF3SU04
            dVU4UzAvZjV0MDhKTzVxWXVZSm90eUEKH9Ki8efdcnkRCgK8JNgjY2XAPZoYCLJu
            3xR1JmuHoo2SgGpujfWd/iiMGmldssH7Nx2JipiodjPpyS4Hffy7jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T10:16:08Z"
    mac: ENC[AES256_GCM,data:fB5PqvIiCd1aAQJXJ8zpfVRp1Jqv2mwyKRR/Tud1IhJ8lFI90ZVdjEK5BMioagSjPoRCSiXWWo8AdVdg18ls+w8Pjf9F98XjjEZxF6ZWRkxtQC/5Q4gUwKpcoKpM579egoPN3dlY2h2BMZ+8FE4Hvy49PVHKFefc49IKafur0So=,iv:rGBSN2mnLsJnZAfyiTquiuINRos7cdjqw0PQBLz/OH4=,tag:cy6WH2ryRGHzXibLR7eOWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
