apiVersion: v1
kind: Secret
metadata:
    name: ferretdb-url-secret
    namespace: nightscout
type: Opaque
stringData:
    FERRETDB_POSTGRESQL_URL: ENC[AES256_GCM,data:av6vs3mQdF7Tb3z9SvfOo0h/OQ30MPm7/dO9nNyRz44HSY7AF+akrPJsm1hslkoDoCfv6obARpnejjuLjFwZdHPaKJb1+do5j9Xp,iv:A2lWs7O3/3SuG7gjggJ8qAYNLdvNnfPegZKKfVcxFE4=,tag:5FHNKiIhQLvYjaiBGJH5nQ==,type:str]
sops:
    age:
        - recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT29QeWt2UnBMNVVWdlZP
            bG5NZEYrZjZ2Zko2eTNpVzhURmFnSkl5UlVRCkhlTWoyVHBuNFNjdTUzb3EzYmdJ
            WWdLMmUyM3dKQjFFN3JiWjBBaURNSmMKLS0tIEJhWUhtMHVEbGpYTy9hMUg3dU9m
            aEZKTjZjcVpuSyttTFZrOU9ua25CUDQKCtQ1ly4g3yEAB/D9+JfqSTXARWrwN29N
            FTEp3DIHkWNyy/gFn/yLAePmRcPi+ErToRvMFmeyBIUgnoMKSRmNiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T19:21:16Z"
    mac: ENC[AES256_GCM,data:QDkhT8KBBQ6KAOpGOIZgs04uHhu5XCGBpCCjSCizlcRV/HNjiEdhfayluYrg7BuadmPk5+KZv4pcZT4jnfitBzziZqEAaE5liU6daZl45xrz0MQ+lJEcU0nwxUwHXd8gAn0WC+aj30hb3xbwoK4Ee5MNYWaS2V1RDWiEddwkXvQ=,iv:fqIL88GOtLctMdy9BEvK+pkeFJ4icuqUIrqp8GXhB1o=,tag:mQtL+Sd/0P1QkkCL+QiNlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
