apiVersion: v1
kind: Secret
metadata:
    name: nightscout-env
    namespace: nightscout
type: Opaque
stringData:
    API_SECRET: ENC[AES256_GCM,data:l2epTZchT+3HnV6kXRfJ5NC6h5kaqpiC,iv:HWE8sxQyfGp9pp1LcWtg7jiO98HPe4qj3mn3n+W3+gs=,tag:aibS6lKCk4+c5FrKHK8+vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmODJlSXl2UWhTR3RwN29P
            VTIxVmkxWXhWTGp0a0pXVmZaeFl1TU4yQ21zCmlaY1laMTZzN1pOdXhoM3VDSkVT
            OE9raHFZUVh0VFEweW0ybjBPbE5pUFkKLS0tIHFlaDRKS0ZyeTdBaWoyeG4wbVJa
            Rk9KRkkxL0NTZjZlREV0S0pSc2dBMFUK3ssEcaSLQpEG7Aam/mE13ad+ADWLt3On
            AarbZHnRwvVigBR+/LhMjvlhP1ecKVb70QkqhgCER4CBv0JkGXYhww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a0xrWnd2VjhkVmwyTTZZ
            a2hjRGhxZkk0bDJjT0g4czl1SGxuNlFVMUJzCitEOFl5eVovT1pFZVN4SHFPbERY
            ak1iMHU3UE5MN20wTkJUdG1DTFVDTGcKLS0tIHNVRVJwYlVnaHFQakhtOENaL3JC
            dlU3UlpnWGJtUDVrVnRNamRldFhyNGMKrJsHLmZSXnAyMBtrtFLuIC2PW72Z3WVK
            dh2hblfsUVn07+bYf5WvzWvAtTHCuo7vNKmC6/mb+0Jq50XRk24s8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-04T10:16:06Z"
    mac: ENC[AES256_GCM,data:xwK148Pdt4tajZZBGvVEDtuJ4kMKo8PFtlPk3CL6g/hvS4S0Li+Xs0HlseS24X8JjcSWICjrjv1WaLElFnv+l36VQDWEBzb5uIoyrbseZ8x9mhc0bKMsbnRW4SWdh7hJyFtOLuYRoHlyF+K1mHyccn8UloqD7LL/N5GK1DWQhc4=,iv:mdZe+xs6vFNz41u92et80xU5sijVvnRu2VeBZlW1CKk=,tag:VWxZDRxLW6YxXUsyrBEAsQ==,type:str]
    version: 3.11.0
