apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:TDC3/dc7fCO6UooIB/Rz/yTW8aDtenxy7u0XVAICxeaJoov+ogD2iYZkCykY2/W+2nJTsfmlCoT7mT21gD1b0oZhEdLUPAlhMSJiUo/OKVKejFAiod20cGnVRlZyQIoNfa1eCRZLbpXWqdl1gpSQv92t8vLznOYmtOna1Nc5OanyMdwtJ/eXdTUk3R3on//kJ9HYI7+0MNhK1gN6X5ro5wRN5dBLEtrTWtxcV51jrOopsSLLoDJWdQ==,iv:yf8baFquyAPb6xnWMm5/OKSx9N9V6ZbXr7y55oFvqsU=,tag:rlVqHqQMP4sEDn3eczXZ8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WjlRVm11R1VYaGtlL0dT
            a0NuaWRnOTIyL1JBVFRPYnNpN1N2QXhJSlVRCjU1U3lnKzkwY09vc3JUdzB5bXVZ
            MXNhYVdUYitiZXFkT1VVcTlNcTdxM0EKLS0tIERmSVkwQnU1cTUzdlV5dkZpc1Z3
            S21rZk1lb2FnaHpnL2EvUUJ5NjZERFkKtrJdAVusLODnFCU0dWtSYEe64Gzj6Oz/
            3K5SP5qttZo8p4xO/IVnlYF8MyIApDCaDLZScYC1l4AikXuBcsNVug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T21:43:35Z"
    mac: ENC[AES256_GCM,data:IEAw6E9GHCyFaHTFtZZfK/a2nLiebIhhAWahWUyPR4dr2+5gwPWWEa5lcKe7Pt741AZfj070ABP22F2h8nVsYbAw3Zv3UGjgpoeL8YLqPTVLWGZMNMU7qBF++u40H4ku6IOm/OicWXTx3Z1rf+QDH+jek6k6ZA7Od/2cMUTd3JQ=,iv:wIxXTMc3gGtX9N8A8xeJZ1IfOaMo/9JVzH/UQJErc8E=,tag:EwtZaY35niyDLP2wMJWy+A==,type:str]
    version: 3.13.2
