apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:TDC3/dc7fCO6UooIB/Rz/yTW8aDtenxy7u0XVAICxeaJoov+ogD2iYZkCykY2/W+2nJTsfmlCoT7mT21gD1b0oZhEdLUPAlhMSJiUo/OKVKejFAiod20cGnVRlZyQIoNfa1eCRZLbpXWqdl1gpSQv92t8vLznOYmtOna1Nc5OanyMdwtJ/eXdTUk3R3on//kJ9HYI7+0MNhK1gN6X5ro5wRN5dBLEtrTWtxcV51jrOopsSLLoDJWdQ==,iv:yf8baFquyAPb6xnWMm5/OKSx9N9V6ZbXr7y55oFvqsU=,tag:rlVqHqQMP4sEDn3eczXZ8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ME1DUTEyN3FRbXpBMXZM
            NWJtVHgzbEFab0dac3I0WWYrZ3U0MXdEc1g4Ck9hMDMvSENSRkhzU2p1Yk9iYWZa
            MEdVL2xXNkU4ckJxbDIyWGViejdtcW8KLS0tIDI4Tm9hMDZpN05XdWdGRUp5ZEcy
            VmxMeFZ0a1FMY3VJZ0VUZWhvVmhTSWsK3FakCTzhVkhEBUvz76+Y5Z5BEBMGUbV8
            jzrFdJmYVyIjVw6X3vO6KSemMVxL/mf297ue1gVjC2OoA2e5QMdaSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcVhPYWJycHBtejBmSmxl
            U0tKUzlqeVhBeTZvOWJnU0wrTFExSExBSlRnCmFMQ1c1L3hxYndSeExmRFl3S09F
            ZW5rSXY3N3FDWk9DWXdMOW5acHpUSkEKLS0tIERxSkpPT096L2pDUkpWR2liRUli
            K3k2cjhweERYUjlZbjNURGk3NVQrbWcKCYsEfaoZKlhMoLOm5j6VHCCmqzDi+wAf
            YLgm0u35joh8oyvj80FOyWTF25KEUxvSzYkbj49AMEVig+ea4PZqfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T21:43:35Z"
    mac: ENC[AES256_GCM,data:IEAw6E9GHCyFaHTFtZZfK/a2nLiebIhhAWahWUyPR4dr2+5gwPWWEa5lcKe7Pt741AZfj070ABP22F2h8nVsYbAw3Zv3UGjgpoeL8YLqPTVLWGZMNMU7qBF++u40H4ku6IOm/OicWXTx3Z1rf+QDH+jek6k6ZA7Od/2cMUTd3JQ=,iv:wIxXTMc3gGtX9N8A8xeJZ1IfOaMo/9JVzH/UQJErc8E=,tag:EwtZaY35niyDLP2wMJWy+A==,type:str]
    version: 3.13.2
