# Django SECRET_KEY. Signs session cookies and CSRF tokens, so rotating it logs
# everyone out; losing it does the same. Distinct from staging's on purpose.
apiVersion: v1
kind: Secret
metadata:
    name: tandoor-secret
    namespace: tandoor
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:QC01HYWS9XU7rPaLteal19L6JBMcrSGfpPkr7FrScYomiFwyQCIBMgs3v8LxFbKHvIA=,iv:nRYO/6fnQqUJDTrvmFHoykArNkDmcAKP4/gqrz8kTVo=,tag:5ECtnL9K0ZByD+22oi/gVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQzdTWXVxNitvd3ZlS3Y5
            SEljZ0JZQm5QZzdmd3E3NHEyN0NhV2M5c2dZClZWMG1KQUlqRU0wdFQreGl1RW11
            YXVrYmZmN1lxZDhwWjFxclJOM0hkcXcKLS0tIFZVMnpqT0JUWUFUNmpsZmc5NUlt
            OUVYc2RuRDFzRTh3VU50bEtodEVTUGsKLmoeHvCi0ydLi9kMM614FN4Y2b4DO82L
            hJ+i8L3yBoeEzUny3KtyoZ+Ln6s3QRXnpni7GDHtPTibgR8Fy0TS0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T06:27:49Z"
    mac: ENC[AES256_GCM,data:2mekA1KCztMbycXDVMEpx1QkWQNL5eqQHx96rB1W2fqG95QYPHUPabs3GhY0pCiZt6HrCWnbNI3tn/zT/3+r/tVmvbOnebEbf+AazI9QDyhztjRPEhuVh5XRNrZJaeKWLfDKUZ8yF0mD2MvpXB93r/awpB9bzRivthUjNH3r0Ss=,iv:o/SUVy0RbvQM83/3SXUuT88nlWit6q1HbfkO6Q2At7k=,tag:ZPP5nZKOoWefmgjLzDdSKA==,type:str]
    version: 3.13.3
