apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.7.2"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Default replica count for 3-node HA cluster
    defaultSettings:
      defaultReplicaCount: 3
      # Minimum 50% of replicas must be healthy
      replicaSoftAntiAffinity: false
      replicaAutoBalance: "least-effort"
      defaultDataPath: /mnt/longhorn
      # Backup settings (optional, can enable later)
      backupTarget: ""
    # Configure default StorageClass with 3 replicas
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
    # Enable Prometheus metrics
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    # Longhorn UI ingress
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.ronaldlokers.nl
      tls: true
      tlsSecret: longhorn-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd
    # Resource limits for Raspberry Pi CM5
    longhornManager:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    longhornDriver:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    longhornUI:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
