apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.7.2"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Default replica count for 2-node cluster
    defaultSettings:
      defaultReplicaCount: 2
      # Minimum 50% of replicas must be healthy
      replicaSoftAntiAffinity: false
      replicaAutoBalance: "least-effort"
      # Store data on eMMC for now (will rebuild with SSDs later)
      defaultDataPath: /var/lib/longhorn
      # Backup settings (optional, can enable later)
      backupTarget: ""
    # Configure default StorageClass with 2 replicas
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
    # Enable Prometheus metrics
    metrics:
      serviceMonitor:
        enabled: true
    # Longhorn UI ingress (optional, can access via kubectl port-forward)
    ingress:
      enabled: false
    # Resource limits for Raspberry Pi CM5
    longhornManager:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    longhornDriver:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    longhornUI:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
