apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o+MefpTNI+pqdzhx,iv:zdIf2zCMyIzTvDsFo1ZISHAtt5DF3lr4lVb9JRIQTkk=,tag:oN4G5xjMKYYEMYBuaQdMlQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZIFEHKdN8I1zQ/K1,iv:/yb5+G5Hf8S66fg+CqvwODXZ5F2nqQA33dsiFJ0WGMM=,tag:Qo/Iczid1kvk9d/fc5DVmQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Glf1Gf6prvlyY6/gM1sorYL+IJlaoQ==,iv:FbNH0CqAcqsk0GK6xth1D5OJ46MXSO/uVuAkz/BJO0w=,tag:2te3IY6bnZOcJHzwd37JoQ==,type:str]
    AWS_CERT: ""
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:WE9YF6I=,iv:cHctVxEpsWyT87G1uDtOjdrD/l2S9kpVp8w7qeLN1/s=,tag:dCm0vcSeWND7pdw+DdYw9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZXFSeDR6VDRMcFNQTkJl
            bnlBZFljTnFKalBvaDU5T0QxdlBvRkJraml3CnZXdHB0b1N5UlgyYmtoY1JKSThv
            OGd2d1IzSS9PczhBbDUydFl3bWhNN0UKLS0tIDRFZDN1ang5MVRhSFpNcnUvcTZn
            UDh1dnY3YlRzcG5KWEozTy9wWWZyaE0KmS8OISoQNpWWQROFpCPqpjVsHkHF1lP5
            oPCfFYxSQNootwrhB9sB1/3MFscG8fLaJAbpFfVLOxu9ETD1GFZM/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbnl4bld6NWMyTmVYR1ht
            OGNZZVg4S044WFFFSTdjb0RPZEo5NGs3RnhJCmpza0JGMHc1RDIxVEZyRWE3TkJs
            bm9DbnNnYlJNdit0eFRoRlZ2eVE4dGMKLS0tIERPaXExMFM4OEg5Nnk1RCt4YUtL
            VktIWDlHTjYwdTZ0MDdQK1JwNGNGRFEKmmh0iqIUYfoaoqVzegAgsoEp6/+c6KU6
            SpIHLUbUVwHDXQCzgqPzUH/B80X1EZLxKCXCOqp0aTt4wkLjuGLEbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-08T20:40:45Z"
    mac: ENC[AES256_GCM,data:sifVi2RqsRcOiXLzmcMpPiJUy3shG75nvBIuAP0+IgM6nwZoslg1iWsGSZ3+wDelSKYd7FMV3fF6ne2VhCSiuGJCgf6OZ0MSeFc5XBmRBKDBlLy7aDC69JcX44UgSgCeC6hhxJfdmee7mNIs0sSDar6H+beVUmZbjOcK3DikT10=,iv:XP/Zn5nh48QoWQPqhfKhRUBn+OWTQrr8pmvXucJ9XOo=,tag:kRlwvcdBTYWWvMOZtMxtmA==,type:str]
    version: 3.11.0
