apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
- postgres-credentials-secret.yaml
- ../../base/mealie/
- pvc.yaml
- ingress.yaml
patches:
- path: deployment-postgres-patch.yaml
