apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  labels:
    name: homepage
---
apiVersion: v1
kind: Secret
metadata:
  name: homepage
  labels:
    name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
type: kubernetes.io/service-account-token
