apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/priority-classes
  - cert-manager
  - cloudnative-pg
  - longhorn
  - metallb
  - reloader
  - renovate
  - tailscale
