apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netpol-check
resources:
  - ../../base/netpol-check
patches:
  - path: cronjob-patch.yaml
    target:
      kind: CronJob
      name: netpol-check
