apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
- mealie-oidc-secret.yaml
- postgres-credentials-secret.yaml
- ../../base/mealie/
- ingress.yaml
- network-policy-oidc.yaml
patches:
- path: deployment-postgres-patch.yaml
