apiVersion: v1
kind: Secret
metadata:
    name: fizzy-secrets
    namespace: fizzy
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:xHVOOemcHAeEBZ9GL437Wa0tK9iyEJ8SqUzQKyPt5stYEmVd9Jl7ytrqixVqHz4KAsfOT1f+9Ty1vxx7IAbY7UAjTeEmf7kRr7Il6r8uP+oGmeIG2jP/pbt6OlGls3GDdDt04JbW2I+3uj64ioYe7UqoZitUcU9Bpox2fedESj8=,iv:WXnNUIC/mTutpy7DPByrWok7aXRdZhmC15T+OMpYXMk=,tag:c7awP2QONqR8N8cd1QZ2OQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:22HiEpG5pRLXM5zBFu3HHOleky3Ku41bcRGXGT5jDmHukXgRw9xvsrK4gA==,iv:GivHbF45O4o9sH9m7TGkYFQKSZ2RQfo3+Rb65JU3OiQ=,tag:z0BitLpX87ezT7Uqczw8IA==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:mfUkDeGywZz2W5QxAGol9T9RnA7Zn8xSa03LZ5Wg4FQVbzgqEsn1LO5tGMc1A8LqBLw0b0EAxhUIOGBdGs3D6Vszuj9BDKpjqxg6rvjvyb8NMhKOY9Ma,iv:tuWgVToeHHSQI8SJE4fGiBY30ErxoYADMwCMF1Ucb/Q=,tag:ncfXk0IvA0wU4aDyqajKsQ==,type:str]
    #ENC[AES256_GCM,data:jfZAee773uQsnvMal8PTO6TwiKI/XTk4lw1wj2SLkjGLoY9YKBTayPlI+QCjSozM7vpVZx2KtnFESY/ulwppe+yWdpQz6F1Kb1M=,iv:mfLHUJz5cDjGfdJQ8NZd/gPPgP7fhLpg5Vku0/SCUbk=,tag:h/9ogsJqz1sD8qUvoTUhQA==,type:comment]
    #ENC[AES256_GCM,data:xDGhgB4WJniml3SwO1JEudHB+R5gey1iNavSl3Pe/YwNqOfx3RjUO9pRBNGD+z3PKTy4xaXEV0g2TXqWpa0Z4KGErwls2PnEhrg=,iv:CbW5ame1UPwSBA9IJf1Bwxj2JBPmGFG6U+HpMDxfkoo=,tag:k0vflfOG7PhVhj4vhMVuJg==,type:comment]
    #ENC[AES256_GCM,data:sq26VNilDwrN9IZLCS1732qO3vfwFuDDLPZ7pgNglStRM0E/VbL2Lno=,iv:Px6T4i8z4F5Mp2vo+6YKZajzTv3Xs/Ov1XZ+RnA/0jY=,tag:0siFRbfhCdUo05w/MWHBfA==,type:comment]
    SMTP_USERNAME: ENC[AES256_GCM,data:QFtpEzphup+UVq4VryW7/kQ=,iv:xY2Wr3xOJRR2wrypdGbLwQ/vJFJCPB85ao4EcBy3iIk=,tag:5ZR2iGq9q+co81D03F4Vdg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:VbsKghRGk1fh38FQv1CN5A==,iv:re+jzcVw8WRvpsp/bLoCSty9HnWLRj8jX1xWlmQViPc=,tag:ZoglGZcr3MtaUW1JCtEdUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb0E0T0t3Y1hVVDJOcnZO
            RVRzOExzSGxZMWpXYktkRmZwVnZuMzBJT2pZCis4TlJ0Tm1nK1BpOXVkSFU4Sk1j
            N2FVWUduenc2bzJqK3RnaWtsNzJRSk0KLS0tIHZIWnlSbUFJNklFSVl5T0VOK0Jn
            NVp5aWNuYUtROGNBTkVhdk44QThSSDQKa8pKgJr4gvfU0L+0yEYF5s0LkXStlaIT
            KBktsRMNQnxlXTNfoANsuhntrmQ/v20au6jtCsNUQKoAAe3TvANAgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:55:23Z"
    mac: ENC[AES256_GCM,data:utr/WHvZsNVWQI4cLeXCxriw2dlwNqpqR7VhyA3yd+2h582mtsW/UZDjsPz4sdnY2kxLu5ukMpfJfgpNrT/AChFXQ3046mV2jhxl7RffNd3zmCaQ7IPqGzyXZyZoaXWiNQ7UJaFmAPuy/1RydR8yYGIbMdwURAhOOZq5er1UrYc=,iv:ddBK2oCCZ5q2agEEXzP1xlu3KVLuVbh553KGM32eoXw=,tag:zIbRw/QREcnoYGRqKsxM8g==,type:str]
    version: 3.13.3
