apiVersion: v1
kind: Secret
metadata:
    name: fizzy-secrets
    namespace: fizzy
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:egaKeZOXGhKDzTKWbv9c8dwQYY148KEjv/2CadbEN4CSduhuFKLe3CoOFfgvTgEiqYQ2fbhQuvf9zTPi+gRSugSZSJdT79qyeGiLN9oxN6myqcaZdLWyGEBM6K08UjtHTaZVmgl8tQlIf/lsqzTYmxRlI27PVfnr0sXSAnB7rLQ=,iv:T6v8KMmVeDmiZ4K5rwO7hRlIm4pm/Tt4SWMe1ZwHlYA=,tag:Y3G1LfswRpJvAxxPNk5UuA==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:Yf/M476XZNXHO9Lza8KS4vIZnTVlXadXorjF+wXQYPXr6Ac/1m4wrqYQ1Q==,iv:sOwH71PVPVDgrpN1OpHIafNq97GjBGW2Q53X2XUedsA=,tag:ZMelCeW7itn9u/k1dObuuQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:57cMkq+T/5oq3EMNjWZa+3bo5uTMdOvOlIhpLRFpQEG4arlgLLOP1ztgqi/ZGMdUbdf9cPN+7eeaj+nQdC+QfmjWzVr2VPQd3GbgxRg0S6EWwMKf/7Qq,iv:zhxqLMAnMnW8+y5HNVMAVW1d0QXTLWCOUuIIINWn3X8=,tag:XXrfhcxJ20fBGTq7rj8nzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUGRiaG5oRjFuUFdoTHp5
            KzdORmxnSzYvSHFzWkFVWk5JVWVucGRKcTJjCkFyckZqb2laMDdHM2txVHhaTFV0
            eUMreEtRaWNEeHk3NGRlUUtXUU9RTzgKLS0tIG1xYyt4cVRaT0tZZFZaeE1mTDFz
            RHBsbFZOZ21tMUhYMVp3c1BVZENrdU0KDk34Nr7+26/KI2+aO+xVzE2udKGxe6ON
            wZ6F2Nf0mYNBvU5PICnnwz0yNucy0cp8IGnGhnHwwLAvLcr3glL4pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:23:52Z"
    mac: ENC[AES256_GCM,data:3a4fmnkbTxzcomvfxsDN9gNzuMK1xtismemSWYT7/K6Fq/QEw5FlPzruZoONe5Rykw9REvRa7uHWiRnPnnBr5HoSx6PiCUF4ooCvWDP/mejCeqXGBTokMzeoO76eQ+kH7ZfjUmUkpTl9QcauqhbqMdBT9AhBPBwVr836bI8PMXY=,iv:6V9Qk067Bzmp6Nh8iZp1XUHjYY6D+QySb8inPt8WEFc=,tag:5PTCbVMPYdUJqjliSvEJKw==,type:str]
    version: 3.13.3
