apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4
  namespace: pgadmin
  labels:
    recurring-job.longhorn.io/backup-daily: enabled
    recurring-job.longhorn.io/snapshot-daily: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
