apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4
  namespace: pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
