apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
- ../../base/ntfy/
- ingress.yaml
- ntfy-secret.yaml

images:
- name: binwiederhier/ntfy
  newTag: v2.25
patches:
- path: configmap-patch.yaml
- path: deployment-patch.yaml
