apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: ntfy
type: Opaque
stringData:
    web-push-public-key: ENC[AES256_GCM,data:XT8vVhYjNAHRDI0ZCwipKrKuN0j4mB6dmbLa7tQuRAxVBvmXKYagdMezl/HYyYfcH7VJkq8uwqbRvDZrFYNJDqHzxe4U2P8dLi3i/Ftd3cz7ZFgncdun,iv:QzM3FQugHgKvGJk7OTfTlz/gmpUoDDA1m+V7hr9aEs0=,tag:A3Mn1Cl0vqSzT+87ky6yYg==,type:str]
    web-push-private-key: ENC[AES256_GCM,data:Ix4Gk27nrzF8dYv8TFEOu5FB7DbD911sidaVwYvo6uOT+wZbrYiorsapnA==,iv:JqtFjDQ5gnvf34SVFn8CO4G57iLbVg1gDjwQkQAyPio=,tag:hN/9Ez4Db4SpcvHMoMFKZQ==,type:str]
    upstream-access-token: ENC[AES256_GCM,data:mI/dfWdyxa7ADmP+p4a8yftDEliPrJDeWGRVaT5ZOoA=,iv:S+1LwSjNAQYkSmyTJcrUDB0xxIfvH99tw0JkShJM/L4=,tag:tYT7AbsxGPARqfHktXc24g==,type:str]
    auth-file: ENC[AES256_GCM,data:fLbwbfQju7zyumdjayFGFGvexE01KCQ=,iv:UKIMScrPHedjGYu2mJvEhbD0BwLWgJHgL/P+zSpJNwM=,tag:l4F0IIFzvGRHOnSWlJJfIQ==,type:str]
    auth-default-access: ENC[AES256_GCM,data:5PrUt8QFJP0=,iv:85bx+aAuu0+4R4i6EEwqgnvQQyhVK0+86GjpSUTA6QY=,tag:p8DjdPIy80SLGOMGqfDPBQ==,type:str]
    #ENC[AES256_GCM,data:gK7wIDb9M8ZFmpPt773hQSaxmxw41Ec=,iv:d5V/lkXql1pTe0kfo07ibxJFv5Ggs2mAypKWzJUOf4w=,tag:KCgPY2NIuXYJsd6Tf1pY0w==,type:comment]
    auth-users: ENC[AES256_GCM,data:u7O2CThoYCY1gvdXBq5aTPtG9rzxLbVClw8EL8GYO9//dzLKElCGjovaDFY/tNr3I8mU+7EF8RKNUxTLYkOFt0c5nIdOOOq6Fw==,iv:h5OskmCK6SXA2TY0u+TjvA08BFAaLdYjMnMUc+i4Gs0=,tag:OX3Et6M6xX7X3DaRWJcFdA==,type:str]
sops:
    age:
        - recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS2JvbkoxNTE2NnlhcXUr
            MVpraFZJK0lxbDBudzhVblJQVXFXQnJlbVNjCkUyNVBuOWJWWWJOZHZTejc5aVla
            c05hK0phcEpZWEpORElncmFlVU5xcmMKLS0tIDgwSXk2MC81eHc5bW1hUVpqTG9W
            aitkZGdVcTIyanlhcWhSMTJ0V25rOVUKZavTLzAynrDkqsi9TUeoSGK72TfOmg0X
            sSa41JGj4+vkt3+zR5BGQtPGDR0cryweiXTEw1TGsuo6tr7YXfwqWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T22:11:58Z"
    mac: ENC[AES256_GCM,data:CQwR3WFVV3uPgIYdTKNWfd4NZL7G8b5dyvJu46LAPPG4dC8euoTfTt3+sAp5H3N25ZGOPjX5CFStpzh0vSYU8z24w3Va5/9zfVc0PyhbJVKCoubTjxePD/LhENhEvosy7o9GX+eQpRcX4jKncDjyoa3TmugZ23Yk18HEWMiscHs=,iv:+lkIG30mSBKvcnjmuNaiZst2R/EhRNP9rOBlCnPGwaQ=,tag:++cIBuImoQL8ZdbX4fNFyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
