apiVersion: v1
kind: Secret
metadata:
    name: gatus-alerting
    namespace: gatus
type: Opaque
stringData:
    NTFY_TOKEN: ENC[AES256_GCM,data:OyDvFczbuKRMmDER+vr1krUodPGCGIx6oy7Fh+AOMzo=,iv:+W8aOvPCzs38HxoZhzExz/AXWpBUlMoIZtLkcDxqjKE=,tag:BsjuuGSqWbUwkMilC0XyJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN1ltT1RyUFAwV3A4WjlR
            dVg1TjBnUm5iS0dydEIrR0xTUmZJNWJMdUZvCll3L2JKcmpCbFAyM1pVZDBNNmpr
            VGFUblV3MnVIL0JLSjU2VnNYUlVlS0EKLS0tIEdKSFZjR1V3SVVveXR1WjJTV0Nj
            bFBKSUkwcWxGSlBVRThRbzFWTjdGL3cKy2B3Ye2JMvui1NkGb32GZX9yq1kf0cZf
            jNcUohJcOwEpHnjTy9VphaCqg10F+O/27ncDzXondsJMsHsKugRdFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T17:29:11Z"
    mac: ENC[AES256_GCM,data:eIWK0eM4/XhH+k7k3B+FkQ2tz34/ycHQZK8x7SOmCEQByELhhtbCuXxXKT4AKTnovsJ9M3auOfrsi0rAtvByxy7mtltrCmmSWWZMetMD324xikPC80cJuKJi1o/nBjPpugWcXU0qHw6yH1+TfqwE1H65EK+nYRxEO+lxxJFfKss=,iv:ojIfaCK8vBiYneD5T5RHnPITCzbpXeIz357aVlEc/Cg=,tag:Auuh779Yv770RmTHIiuU2g==,type:str]
    version: 3.13.2
