{
 "title": "Speedtest tracker",
 "description": "Speedtest metrics of the internet connection",
 "tags": [ "speedtest" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Download speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(speedtest_tracker_download_bytes) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(speedtest_tracker_upload_bytes) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(speedtest_tracker_ping_ms)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_tracker_download_bytes * 8",
     "legendFormat": "Server: {{server_name}}:  {{server_id}}"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_tracker_upload_bytes * 8",
     "legendFormat": "Server: {{server_name}}:  {{server_id}}"
    }
   ]
  }
 ]
}