apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/network-policies
  - allow-campfire-status-bot-to-k8s-api.yaml
  - allow-campfire-to-nightscout.yaml
  - allow-gatus-to-grafana.yaml
  - allow-homepage-widget-targets.yaml
  - allow-grafana-oidc-egress.yaml
  - allow-status-bot-to-prometheus.yaml
  - cert-manager
  - cloudnative-pg
  - external-services
  - flux-alerts
  - metallb
  - tailscale
  - traefik-default-cert.yaml
  - traefik-helmchartconfig.yaml
  - traefik-https-redirect-middleware.yaml
  - traefik-local-network-only-middleware.yaml
