apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/priority-classes
  - ../base/barman-cloud-plugin
  - cert-manager
  - cloudnative-pg
  - kyverno
  - reflector
  - reloader
