apiVersion: v1
kind: Secret
metadata:
    name: campfire-renovate-digest
    namespace: campfire
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+tNT7svDwu65r/AtSBD2Lc63VFbpa5p0X6tAqS/uevE/PdwcHN/jRILUcLMz3PiP,iv:yfUS4ipOkI4x1UZstkAuYCkbNeAypS1zy4N7a8pnQmE=,tag:eKWxQl+m3IckcEkG3OyXow==,type:comment]
    CAMPFIRE_URL: ENC[AES256_GCM,data:4k1gin7LWOaKrFv3q3BJI7o0iUYJNocgQJQHJdWOk7D06a5G3gq05dTsBSGaX7NCMID3Q8SaJFx3j14qliJiUgO5VZAEZCrYHRM=,iv:B4xE9/W2bGVtLYcpFIBaoeDcGBSTI0xwxRaFV3xdolQ=,tag:5Q/NEVErv3zKEVqRjPrkzw==,type:str]
    #ENC[AES256_GCM,data:XPdaR2hYag0Rso/ZcqNhgXk+b6QLhHJKO5LzK9RmGqFfcdgE+Tv7b0Eh6i/94f+XkyMR8pBwiHN5iGjygoedDz+QJrGoZB2psc22og==,iv:PlgnLKUMS4V1iNutPh9ZIVawZg3+7FaEuK1nls+Aamc=,tag:wAm5yZaz90K8WWZ6k4/APg==,type:comment]
    #ENC[AES256_GCM,data:4GSzXJO4TwPJTpkFXlOUE3OBFDMla2/ySwVduC1I/dwVWhPo4M13wpPblv7tdg==,iv:RAazOKo5CA4xKdwv8/YmSvVtQxbxdkhXEROz4Y5fRPM=,tag:8R+OROfOWkooBE1rMBhcYw==,type:comment]
    #ENC[AES256_GCM,data:ZhznDyBEnuCbG837BxoVRul8P0FkvZE95x4W/prxZ5mvLMbF4JU8WxFMxGVWdcPm1lpYg3/ohYfhR3fQYeYIgavee4UEIveec8KjQg==,iv:8EcS1oewdHSk2Z0fdSFJkJAiKJ1yks8MTvDvEF60CcE=,tag:XE6Lx9JG1EkAh2HS2IzCEQ==,type:comment]
    GITHUB_TOKEN: ENC[AES256_GCM,data:OhKpoDFTu5VAJ+VHw5FlTCLBSwfZitq4Lk0Vq0Tca9J0SMnfPgOAx2OQm7AY1ov4pi3s8sbhwsASzFUFW67YafpYznCXTz/1vRpqubmTeCIs2qUBbAd/atA577dU,iv:zSOPdUqref8x5bR6kK3hgPz6nZ6MNVothMrs7oc5lpM=,tag:w2bk8ys8nnZLJt9w6xpAXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcncrN2hQYWlyRVh3RUFi
            TW9OK0ZRRjBTREdGM3I1YjRTbW94akl2ZzNjClY3bUFtcmFnK1ZlOFJOUEszaTRN
            Um5FcmhFUE4zcUM4Umx3UnNMdTBXakUKLS0tIE9hNHlxYnoyN2pvRXZ2ZmJrYXVR
            dVBTQzJ2cFZFcUxxeXRqbXBFUHNMSkEKEV/KJ5NGq7YZhzAPh7OmnbIsdqtTcgIJ
            wivxqenfzfUuQDmp4fPqIU3v9f3i+pYSGy7gSL5nvQPNitu0gd2nGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T22:21:39Z"
    mac: ENC[AES256_GCM,data:SnAniR/ZmvMOcWr9yEEK2WnA4L8BiEx4Rb80JG54bUKx2wUkqUbEKw1Fl3eL5H/FlG7CoV1AmgRWN8xboBk3yCq50inqdgRSizM7MDff90Lp5fGbQ12e6xCWsaSa3yJ9ClAiByq0+9BjiYlogdUbBBGARTUMqHT8EKHIG+Ru5Ko=,iv:FarVsz4UV7wxagfPaqQZTca9GJMly2XoRSLcdNTfYjk=,tag:Qk6n/Lu14bW/yIPlvgF1pA==,type:str]
    version: 3.13.3
