apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "6.49.0"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 2  # HA with 2 replicas (3 nodes, can lose 1)
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      querier:
        max_concurrent: 4
      pattern_ingester:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 30d  # Longer retention for production
      compactor:
        retention_enabled: true
        delete_request_store: s3
      storage:
        type: s3
        bucketNames:
          chunks: loki-production
          ruler: loki-production
          admin: loki-production
        s3:
          endpoint: http://10.0.40.10:9000
          region: us-east-1
          s3ForcePathStyle: true
          insecure: true

    deploymentMode: SimpleScalable

    backend:
      replicas: 3
      extraEnvFrom:
        - secretRef:
            name: loki-s3-secret
    read:
      replicas: 3
      extraEnvFrom:
        - secretRef:
            name: loki-s3-secret
    write:
      replicas: 3
      extraEnvFrom:
        - secretRef:
            name: loki-s3-secret

    # Disable embedded MinIO - using external NAS S3
    minio:
      enabled: false

    gateway:
      service:
        type: ClusterIP
