apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-secret
    namespace: monitoring
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MpW50D6srpjRYlBh,iv:k5SSaU2538t04jvTPw4M4ah44PELZO82D1h6GZLUA0g=,tag:6h2AbECsme+fvCQ1gztBQQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:T4gMCSSBn8mrhxmT,iv:Al3lJS1zCDJ/LK9sbQ2nOc4+K/Fre1lzTVB9pl4tU2I=,tag:YLSZ9ZPmxZEmyH+I9c/wLQ==,type:str]
sops:
    age:
        - recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMDBYaXZZL3lveXpwK0Ny
            UG5RWjhOZE1Gd0t4dzVMUjUraXE3K3NaYXdnCjFSYURrWlJsUWFtRFFBQTZQV0VF
            TEh6R3dSN3NpbGZXQ2ZmMkVPQW1QSEkKLS0tIEt2OWRJZXJBQk1QdmRmTE8xbVlj
            cjhnMEFCRjc1emVpTDgxcDJGU3Rla0kKNq1L/osuKfaHJlxciFjwgkUPWT39oxuh
            YFuVtdYugjJuW6StZN4VowabrpPtkPn5DRTG+gCCit4O55D2t1ubJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T17:17:18Z"
    mac: ENC[AES256_GCM,data:zwLgjwAV2Xk3gmabmhlrEBsg4ztzpE1y8JztTfrcD1O2WTyVW2Jy9brgif3Z6g6ghblcwRU0mqDtKcmndyYcQpBUz/wOgf9mF0RkAxEnqoyxjpOFoWjdVCfDhXBpIkys7+CnC1xs+ij1TXAMNUzcjbIqDX9l0FL1el7Uj28P934=,iv:Cvj13Yytu+3Rm6DA0RcOVQmZOL8CgavkP6MeELCfYVg=,tag:tU/jIKIzdw7eUBrBAX7QNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
