apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-secret
    namespace: monitoring
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xraWot3qPH4rOJlg,iv:aSZJly60I0ysBxnk0pwDZ40iew9hGNOBdFnqHhE2Euw=,tag:E8wH5g/tMUztDIAU97vZkg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bsnONNx/hWnC6gQB,iv:uGqJQ+KkImnKDjFTLtM5p83l1WfzaG9moUh+Uyr0dGU=,tag:g15XrU0Ed+yHbrPPp7IPLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUkJqMFlod215Rm90Z2tD
            TFEvNDFDdVcvRWxsdGdEZktSU2ZHajRjZWlZCi9sN0pTNHRLdzk5RkRCL1luMWpo
            TGMvSlQxL0tlaXBQaWZ0WEJ5aUZDN28KLS0tIDI4aFo4Wmo4dG1UZTZITE9TUHBx
            a2VxdFpMNWJaRUY2a0pYajFSOXI3SzgKnUUfmzB+Y9VZHzgRq8ZcbVjy3lnTzs/P
            kPhOTvkvChYmyzQuXdjzHXMjgCLFegHDP2pYeNHqrDgPjVfeMeukIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L0JIc1ZSb1dQTmdJb1FO
            a2dRTTZ6SUR6dE5FS0g3SUVoR3dnT0tDZmk4Cml1b2M2bXlRTUt3SjBWRzNsK3VJ
            bG0yNHZuMGM3VmpnWVZOZTFWSlZXT1UKLS0tIERLdDlqUDd0UmNMM3hsNlN4b0x3
            Z1BLN2FQVWdvWUNSa0lpVDU5MHVvN28KM1H8HezR5r9QHPT5vPZep5Fe+nZ9fg2B
            +aVNXbVoosOOoHpw47qX2SxzV/guEnXwSL0n8JXFd3mgqXM6D/RGVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-17T18:06:08Z"
    mac: ENC[AES256_GCM,data:SEki3Je7uAq4fV4gJCue8kJxPhXkYUCFaa6WkygexNyjvbgqhX2MCS/W4oLswfwBLTPd+ASxaW9j8FN849LYszR6YzOMGgmFYyUIhoggnl/KzxMgs/cV2c1LvgV0ISjyCoYQ9eaNmFZnvmKt42P04210w+ja1Oc3ELNNhSAb3sw=,iv:Hf5dCVj6O5e6eAEHZlZupNV+SS+OR9eLqWd9BS3BKd8=,tag:tQLGLi0BeGxi8USStNDfUg==,type:str]
    version: 3.11.0
