apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.10.3"
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 12h
  values:
    # Global image tag
    image:
      tag: v1.122.3

    # Immich-specific configuration
    immich:
      persistence:
        library:
          existingClaim: immich-library

    # Environment variables for all components
    controllers:
      main:
        containers:
          main:
            env:
              DB_HOSTNAME:
                value: immich-cluster-rw.database.svc.cluster.local
              DB_PORT:
                value: "5432"
              DB_DATABASE_NAME:
                value: immich
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-user
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-user
                    key: password

    # Server component
    server:
      enabled: true

    # Machine learning component
    "machine-learning":
      enabled: true
      persistence:
        cache:
          enabled: true
          type: persistentVolumeClaim
          size: 10Gi
          storageClass: longhorn

    # Redis/Valkey component
    valkey:
      enabled: true
