apiVersion: v1
kind: Secret
metadata:
    name: b2-credentials
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:woGwEUq0mSGN0twaIcH6+75UMW5yiBx66Q==,iv:6aAaR7m4V5dyMp507ImtZA0sDb+gKwNMimirC25C1lw=,tag:BIi4N2tUuM6c4zwJGUXmHQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:BO5xdMtDQ0yo6PJjuHLR5hziy7okeX5L8dA+eUFCMA==,iv:UFPfNSZB2VULLFNjdK1nXlZreVplJpIR68qR+MoPqoc=,tag:KyqKk/xhLLZO57NYTy6soQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d2FnTTNlOVBtdWdsMHZE
            dndndFh0d1dtc0xTc1B6aU1UYzcrYXZZK2tnCmpUY1hYTXMyZlM0Z0kvYVhBZFF1
            T0syZlF5dlVxdGhTajBDcU9JUFMzR1UKLS0tIFdSV2ZBaXp4Z3pWanlXaHpGYXBj
            QW1kSFRCdTRURWV3MFdMV2VUc1FYUUEKzuosUccf2crVEEXkTKVfD5cSdBgQ6rs9
            DJbhwUoHlxYra1gNyriWw8Yx5nlUBZ9yu4v79yFDNoEMT1fg2T752w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZmNvUTdSaWNZbEpjcWda
            NGdVcjNaZ1VvQW1jK1cwb1BYRlY4RFZFYUFzCi9YWHF6Qkh2UzFnaHVITnpIU0R4
            YmJNTUVKZ2syMUJiaUtwYWRBL0NiaE0KLS0tIEI1L1hwRGlJRkQwWHVCTFZ2aFNO
            SmdjcEdrcHREaVFvQ1Fua0ROUTl5dFEKWtDkJprAjPMQbIhljZhV1vcu18/j0ri2
            O3cshID+uJ2+pN9M7+Nhe7fOYlbTYW1OcXbP15Oda6+0IojFDYNpNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14jzgqqg2c008ty2leafhduq77p7lyh9aw46wasygf9jmly3wse0sx7sf4u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-03T22:42:03Z"
    mac: ENC[AES256_GCM,data:V5d7p82Oq9W/cVnQLTIAFxI9k3huksKTYtc7MxU1ZMmP3ibQNY3oft8P3P8COEmLF/QvvJVWdJUszLOkOIbOBVFjq+rCqbN9yZNA+SHaDatLZTxlz4DeWrIu5tw+NDoDra2Cl/wCfUf4SE8hNP3BIbCC4g6qaFK4nZrm6H3I52U=,iv:anb9w8/J85UA0YYQMKZ3ypXB4Ccq8UxH+M1L4M9V13I=,tag:lkOYqe7qHImotG4cm2rUpA==,type:str]
    version: 3.11.0
