apiVersion: v1
kind: Secret
metadata:
    name: pg-role-commafeed
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:dLppCWA3FaAt,iv:2LjiOD83oY4BCoM36L54DIL3yxyrODghQhHzNU3qmcg=,tag:xXxMtCMMT5z8DlGiDFKQpg==,type:str]
    password: ENC[AES256_GCM,data:UV2E8qUya0Ci3CLGqeaVHvaAszzWuAHCwfbiQVksOxQ=,iv:WJugzuSKGsUFGvN4Kov6zpUkdvRq5FtCLIcFzLmEAcA=,tag:JocsXn2r7p8td90M9jy0+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-linkding
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:2luTaYLCYVY=,iv:ljmkGA0XFaMaKLc12Ftd0j5cxOJtAGM/pHH3wLc5Z0w=,tag:ACMAuUJyeJP7N0utT5p0og==,type:str]
    password: ENC[AES256_GCM,data:bTVZOqxkGClzJt64eTmxhiJ3lBvTFaiRelsmof+qNOI=,iv:tbPK99bnb9KKf5+2lRtWUVMHqJ3XWq2k+QG25336jJg=,tag:nEhpk9fYLuXHjxJ2eER5gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-tandoor
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0y5rqA9C3Q==,iv:E/yEUt+hnrjmqfuzncyKmpzxSCsSKjHQe21how5TlcY=,tag:yojNIOe4/0B3GRGQ4jOJtQ==,type:str]
    password: ENC[AES256_GCM,data:zwk4ohnpa49BWpt2qDBWO/3TZubHtnCkFpSQvZB+yFA=,iv:ducQOhalQTU0Qgi9qSjhyh0zvZDpvvviUUCGLhOI4G4=,tag:H7iajDFCP0/5YxIstrcpRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-gatus
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kFQuGkE=,iv:Fjrxht3W91pz7l2OWTqHK0qKuJ2dFvYMiY3PBZ3a0CU=,tag:jhDmMSBjQQ6p/fJmA/WYOQ==,type:str]
    password: ENC[AES256_GCM,data:dxf7l5rPo6kiQAPu68+PdIveHecIHmlD+37ZOYE0ibM=,iv:NIY296M+9P2XMG5vLYq4xJPTyA/7tjKn8m6cf7RU4VU=,tag:kNJ9B47Ig39Mo6UeCe2CSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-nightscout
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mtvzYbUVKKEaUw==,iv:4IhAe/Y7jF7BP8ddqC4uEUawR8uOGLPwIjjfr53GI3s=,tag:5geiJsbagb8nbvNshhs4xQ==,type:str]
    password: ENC[AES256_GCM,data:UtIW+9IkPQau+FpjztxcbJ6l6YZiOfd6hMXrGpmx+yA=,iv:+Bor9n+DQXMFo9Xio/KktpqGE4k7wC6Na6EfaZ3deHk=,tag:3m/Hqp9NZqgovv1Q0gpW2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-speedtest
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xq1Mc6meBDXe,iv:L6emCtQAujE91spHOUkIXkxdp6KbHt/ZtDJLU81Vv/Y=,tag:BetJDuz260xRwr6Ev4Ohqw==,type:str]
    password: ENC[AES256_GCM,data:8bHCRbl2RMEhZAgvjPIxzq2pnHOpBgMDRyoQN2iQhtE=,iv:BQeClWNH4c9xHId5PNA36fx6DMvyyauICTIt7AmtcEU=,tag:Pev8quAr7dhWVW5dwStkpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-authentik
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:D4ZPW5ubStxa,iv:0okmDaEGKhAFfNnRQx4sUOhDosd1VWahQZOH5Uwv/PI=,tag:mgT8mUHRcZB/eYLytTkyng==,type:str]
    password: ENC[AES256_GCM,data:9AHVZaXv6mLIiW9caBZRb8XdzLvg7AhttKA0cUkYZq/tvy17v5UtJn93RrhNIjY1,iv:vPVyx1w83aRz8xLhqE/aMaLKNj64MG1AnffwsM742ko=,tag:ix7d749P3CXYh8h1wGon4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-bots
    namespace: database
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: campfire
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:gssiNg==,iv:VqhqoTQoKIIxaP5OMWdhk2ytOa20RqukiRr3WoVHLdM=,tag:Ep0BTZx6zzTK6UBDC5jR6Q==,type:str]
    password: ENC[AES256_GCM,data:xnlgvHuQNZmXpAYZ7pTlixNfEQ2uXEkEllnmdXeX9N8=,iv:sjTrWPs7/kf7uba7HhEYmc9QxrRtsqppV6kxkhngLPw=,tag:kYtRARND0qwWpqACzQ1k9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-role-squirrel
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nMUXuglEH+U=,iv:+7DEzbZZCpT0QjZ0XgA698C6rOnEO1ebCUt/1na9Qqs=,tag:Sxzz2w+19PEthSBWrwGzNA==,type:str]
    password: ENC[AES256_GCM,data:criorU7ykdt+EMqJfEjJnUqWYGJPatauCZFTKrcv18Y=,iv:jL0EN2G80BrsDW/FJ5RhELgDvfuitYLGhx+EzZqMz+g=,tag:tcwJzFN66kgx+oFCjZVNTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajQwc09MOVFSUXRsUVZZ
            Q1A0YkZ4NHNtaTV3MHRmd1gyMzNlV0UvUGtzCnhQUkZpUGhlcHJaS0M4QlE0L3VS
            M0ttcjRmb1hTVWQ2a2dEdlZZTnlPOHMKLS0tIGtoMzAwZVRGNUxEWVExWXNtNXF6
            eTNxanJYZExCa1Z5RHg2amVjNnhNZVEKYQtB1H1+QCzd7LES2hUOkuPsNmNmV+4U
            BkKgxSVp/nrnEVPHajmT4QXHg0FhGqpCugy+Vqyr/SB3UT6VGOVhmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:48:50Z"
    mac: ENC[AES256_GCM,data:oq46MmTFTjrSIF7egGhAvPNAa5FNSUFQ9xTOL69S2n8JyT1DNZXAOnhapFLQ+KWU15bnycLCCsU+ukinGAYajLsiBiVx66xFEfF3SIEfuaBmKzy9yDO9blxYVlcBfI+VuJjSMX7Bf64thG/nOIFYwRozYLltUzrP3y4MMjztmfA=,iv:1e3EZD81j7iNWywHcmPztjxBlHpqpXH79ExWUvnFPmo=,tag:fDFl8APDd3oxanIwCBxVGA==,type:str]
    version: 3.13.3
