apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commafeed-data
  labels:
    recurring-job.longhorn.io/backup-daily: enabled
    recurring-job.longhorn.io/snapshot-daily: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
